### ISSUE TITLE
Need Test account option.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#1222]
-Need testing account option also here.
- When send from contacts.
![Screenshot_20200730-163922_hexa dev](https://user-images.githubusercontent.com/62699947/88916227-56617e00-d283-11ea-9375-25e7823e11e2.jpg)

**Comment by CypherPoet** [comment]
Is this still a feature we want to implement? I'm not seeing where the UI currently allows changing the account to send from on this screen. (@AliMeer @antuz123 @Arpanjainson)

**Comment by antuz123** [comment]
@cakesoft-swati - when do we get this screen?

**Comment by cakesoft-swati** [comment]
- When sending through F&F list contact.
