### ISSUE TITLE
-Need a way to differentiate between pending and confirmed transaction.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#1223]
-Need a way to differentiate between pending and confirmed transaction.
- We will not use number of confirmations on this list. Only pending or confirmed. 
-Will need UI work.
![Screenshot_20200730-164424_hexa dev](https://user-images.githubusercontent.com/62699947/88916634-0b943600-d284-11ea-83d6-17abc47d8560.jpg)

**Comment by hemantsain** [comment]
Need UX like how it should looks like for pending and confirmed transactions.

**Comment by antuz123** [comment]
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/ed02745a-fcb5-4ddc-bb0e-a32a9e65a166

**Comment by CypherPoet** [comment]
Some of this is related to https://github.com/bithyve/hexa/issues/2269, and in either case, I think we need to know the latest design and UX requirements here.

(@Arpanjainson @antuz123)

**Comment by Arpanjainson** [comment]
@CypherPoet  refer to https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/3fd27408-aa14-4022-b52a-0f4641c1f866

The spec links will be updated in 1-2 hrs.
