### ISSUE TITLE
MO1: TOR enablement

### ISSUE THREAD

**Issue by Parsh** [bithyve/bitcointribe#1241]
This covers tor for both Android and IOS.

**iOS**
- Look into iCepa (https://github.com/iCepa/iCepa)
- Investigate zap-iOS's code and whether we can incorporate that in our app. (TOR PR: https://github.com/LN-Zap/zap-iOS/pull/272/files)
- Another iOS app to investigate: https://github.com/chaincase-app/chaincase

After research into available options, we have opted for replicating Zeus' implementation of Tor.

-----
Screens names with xd links to follow
-----

**Comment by Parsh** [comment]
Update: Socks proxy, therefore tor-request, isn't working inside React Native env(probably not supported).

**Comment by Deveshshankar** [comment]
Completed
