### ISSUE TITLE
Transaction details screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#1326]
-Is there any way to figure out form whom I received this ( if it’s send form existing contacts).
- For example this transaction is initiated by ABC, it should be intuitive to know that I received it form ABC.
![isthere](https://user-images.githubusercontent.com/62699947/89791316-c3f19200-db40-11ea-9c37-de9f58d4b636.jpg)

**Comment by AliMeer** [comment]
@antuz123 This is from Aug. Please check if its something we want to do pre 2.0.0

**Comment by antuz123** [comment]
@AliMeer - we can do it later.
