### ISSUE TITLE
WI optimisation

### ISSUE THREAD

**Issue by Parsh** [bithyve/bitcointribe#1793]
- Modularise/granularise the component being encrypted and backed up such that they can be updated instantaneously and asynchronously post user journeys (ex: TC initiations and approval, New accounts addition, etc.)
- The WI updation should be done from a screen that is instrumental to every Hexa session(ex: home screen) while the non-critical components can be updated at the end of their respective flow(such as account states in terms of bal/tx/utxo/indexes).  
- Should be done once AC management is in place to avoid database and restoration related re-work.

**Comment by Parsh** [comment]
Would require database changes(migration to Realm DB) in order to implement WI sync granularisation.

**Comment by ASN-BitHyve** [comment]
@Parsh is this still relevant or can the issue be closed?

**Comment by Deveshshankar** [comment]
Completed
