### ISSUE TITLE
Database Implementation(Realm?)

### ISSUE THREAD

**Issue by Parsh** [bithyve/bitcointribe#2132]
Need to implement database(migrating from SQLite to Realm?) in accordance with the schema defined as a part of account management.

**Comment by AliMeer** [comment]
Not part of 1.4.x releases

**Comment by AliMeer** [comment]
This can still be considered after 2.1

**Comment by ASN-BitHyve** [comment]
@Parsh is this still relevant?

**Comment by Deveshshankar** [comment]
Completed
