### ISSUE TITLE
QR to work with an external scanner

### ISSUE THREAD

**Issue by antuz123** [bithyve/bitcointribe#5037]
1. The QR should be scannable by an external scanner 
2. HEXA scanner should also be able to recognise it and directly start the flow (without having to jump to the webpage) 
3. If someone does not have HEXA, the QR should take them to the store for download
4. This should apply to all QRs excluding the address QR 

This would mean having the deep link on the QR so that it can do 2 as it will have all the info, but when you scan from outside it will go to the store (3). Ensure long deep links also go to the store if no HEXA.

**Comment by cakesoft-swati** [comment]
- Verified this on Tribe app v 2.2.7(606)
