### ISSUE TITLE
Hexa website revamp

### ISSUE THREAD

**Issue by mide66** [bithyve/bitcointribe#5973]
### Landing Page

- Heroes Section

Hero text needed

social media icons- placed at footer

Features section needs to be a slider to reduce the length of the landing page

Centralize the youtube section as it is different from the features section

Contact section- email address and location should be at footer 

Leave us a message part should be refined.

Footer section- It should be refined, the tweets section should be brought up.

---------------------------------------------------------------------------------------------------------------------------------------

- [ ] Banner image depicting the full fledged home screen plus the hexa logo required.

- [ ] Replace the image on the left with the internal view of the Checking Account and the image on the right with the home screen that you'll be keeping for the banner image.
![ss](https://user-images.githubusercontent.com/68264080/188435881-94a08be3-f3bf-4847-8503-50031777364b.jpg)

- [ ] The Whitepaper to be removed from the website ( Its in the backup section) - @akshaytikle 
- [ ] Backup section Text Change : Headline: " Easily backup your wallet with Seed Words" Sub-heading: "Never lose your bitcoin" 
Body text: "Backing up your wallet safeguards it against theft or loss of phone. With Hexa, you can easily backup your wallet using Seed Words. Using seed words ensures that your wallet’s backup and recovery is not dependent on your cloud service provider. Please ensure that you safely store your keywords. You would not be able to recover your wallet if the Seed Words are lost."

- [ ] Image depicting Lightning Account feature
- [ ] Image depicting Seed Backup  feature

To be kept Ready:

- [ ] 2 images depicting Satscard flow - 1 that shows the Gifts section with Satscard highlighted. The other when a satscard is topped up.

- [ ] 2 Images depicting Sherpa flow - One that represents the Sherpa’s FnF section showing their child’s wallet. And the Child wallet’s dependent wallet terms and conditions screen where the child could accept or reject conditions.

- [ ] Shifting to Wix - Akshay

**Comment by Deveshshankar** [comment]
Close
