### ISSUE TITLE
Redesign Multiple gift option

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#5982]
We need to think on the placement of multiple gift option because User can't find  multiple gift creating option easily, may be it is on top and the setting button doesn't indicate that.(to do backlog)
![Screenshot_2022-08-25-13-16-54-64_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/186621326-78dc49fa-c5de-47e2-b84b-fed154dc60ac.jpg)
![Screenshot_2022-08-25-13-16-59-24_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/186621341-3af3aa81-8ce3-44b5-9f7f-de1443fea6d6.jpg)

**Comment by mide66** [comment]
https://xd.adobe.com/view/ebae18ce-2577-4d53-9b75-cb9ae5317eb1-befd/

**Comment by Deveshshankar** [comment]
not required
