### ISSUE TITLE
Banner image design for BitHyve website

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/bitcointribe#6071]
We need a banner representing all three of our products for the company (Bithyve) website. Please create one and insert the Hexa home screen image. For Pledge and Keeper, Devesh to contact Summi and Jess.

**Comment by nik132-eng** [comment]
Hello @ASN-BitHyve sir,

can I start my contribution from this PR? need some guidance because this is just starting and need to understand the codebase also.
