### ISSUE TITLE
User can share QR code 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6099]
1. Can share images of Gift QR as a gift (Not working in IOS)

**Comment by Deveshshankar** [comment]
Need to check in ios

**Comment by Deveshshankar** [comment]
Not Resolved

**Comment by akshay8551** [comment]
Working fine - 
https://github.com/bithyve/bitcointribe/assets/61345820/9611c8a1-6278-4dce-8f23-46d22f9c06f2

**Comment by Deveshshankar** [comment]
Need to test in iOS build

**Comment by Deveshshankar** [comment]
Only text is being shared No QR code imaged is attached

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)

**Comment by Deveshshankar** [comment]
Completed
