### ISSUE TITLE
Multiple account List is missing in Design (Account Detail)

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/bitcointribe#6193]
Users can create multiple Accounts & check their wallet Balance

Send & Receive Screens is also missing

currently, Account detail shows single account.

https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/f208c111-49c0-4d1f-b4b2-7b5c003a3189/specs/

**Comment by summikhan11** [comment]
multiple account screen already exists- nothing will change there


add account: https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/b55a662e-19d6-44d5-b0c9-cef5e2904b04/ (i'll add illustrations later)

receive: https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/d1751fc3-f634-48ff-b816-ff6f40e9a5cf/

send: https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/b93e6885-1a73-48fe-8ec5-b61d236dac89/

**Comment by Deveshshankar** [comment]
the old design of hexa is not required
