### ISSUE TITLE
Chat Flow need to implement

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/bitcointribe#6195]
Chat Feature Need to implement & follow new Design.

https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/65a99322-0199-4720-b831-b8ec04e1e385/specs/

Users can send Sat directly to F&F contact.
Need to follow Best practices for UI

**Comment by Deveshshankar** [comment]
the old design of hexa is not required
