### ISSUE TITLE
Modify UI of transaction history

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/bitcointribe#6200]
Need to modify Colour Codes, Fonts & Icon According to Below XD link

https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/6189d0a8-68b0-4648-8070-842921168e63/

Screen no (76)
Need to follow Best practices for UI

**Comment by BhuvanAde** [comment]
Can I work on this issue?

**Comment by kkartik07** [comment]
@Pawan2792 Can i take this issue?
