### ISSUE TITLE
Gifts screen

### ISSUE THREAD

**Issue by bhumireddy99** [bithyve/bitcointribe#6204]
Need to modify UI, Colour Codes, Fonts & Icon According to Below XD link

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/85e9452c-97b6-44c2-8a75-2ccc9a616ee4

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/9197783b-5b72-4ad8-9902-0911721121b4

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/40fe10ae-61ec-4571-8760-d131c9f9e2d4/specs/

**Comment by Deveshshankar** [comment]
Fixed
