### ISSUE TITLE
Modal views inside the app

### ISSUE THREAD

**Issue by bhumireddy99** [bithyve/bitcointribe#6206]
Need to modify UI, Colour Codes, Fonts & Icon According to Below XD link

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/da64b3d0-7b5e-4f6e-bd9e-1e52f922b492

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/f70cfcdb-9355-41e3-9025-36157d940884

**Comment by Deveshshankar** [comment]
the old design of hexa is not required
