### ISSUE TITLE
Gifts and FF invite screens

### ISSUE THREAD

**Issue by bhumireddy99** [bithyve/bitcointribe#6207]
Need to modify UI, Colour Codes, Fonts & Icon According to Below XD link

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/dd808262-80cf-40db-940b-4e65df1c23fa

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/acc0fb5a-0498-40b5-bd36-a3c9eeaa9f95

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/9aa1f09b-16cd-4f0b-8145-cc0423c2fb00

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/aad2e8d1-8302-40ef-be41-a7b79c2845c5

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/340783e3-b6f6-4243-90d4-9883caca0c28

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/f8f8f4ec-1c11-4e03-b9ac-2e4f956e6245

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/3c62a3be-4a85-4acf-a181-169a45ebf0e6

**Comment by kkartik07** [comment]
@bhumireddy99 can i work on this issue?

**Comment by Deveshshankar** [comment]
the old design of hexa is not required
