### ISSUE TITLE
Buy bitcoin screens

### ISSUE THREAD

**Issue by bhumireddy99** [bithyve/bitcointribe#6209]
Need to modify UI, Colour Codes, Fonts & Icon According to Below XD link

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/1f19e60a-1a26-4d5f-9368-ab2de9712d6a

- https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/b8fb5a2f-1398-4344-be23-3bc59de84b07

**Comment by Deveshshankar** [comment]
Not required
