### ISSUE TITLE
Login Screen UI redesign

### ISSUE THREAD

**Issue by GourabSanyal** [bithyve/bitcointribe#6224]
[Screen 1](https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/specs/)
[Screen 2](https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/53bb06ec-7b77-431a-88c1-f130bf5a2703/specs/)

**Comment by kkartik07** [comment]
@GourabSanyal Can i work on this issue?
