### ISSUE TITLE
UI improvements & Responsive 

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/bitcointribe#6236]
UI need to improve modal

![File (1)](https://user-images.githubusercontent.com/99478432/204492782-ae4d6d88-148d-452b-be6f-0cc473912e98.jpg)
![File (2)](https://user-images.githubusercontent.com/99478432/204492794-75902d55-ba1e-4674-add7-af8f9ee594fe.jpg)
![File (3)](https://user-images.githubusercontent.com/99478432/204492806-f1263606-9b38-4275-b31d-d9182806f5ca.jpg)

**Comment by kkartik07** [comment]
@Pawan2792 can I work on this issue?

**Comment by 9520prashant** [comment]
Hey @Pawan2792  wanna work on this issue can you please assign this to me?
