### ISSUE TITLE
wallet Account UI & feature send & Receive flow (Rebranding)

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/bitcointribe#6237]
https://xd.adobe.com/view/81a8ea3a-75a9-4eb8-9da7-b5a41d617d7a-d4fb/screen/f208c111-49c0-4d1f-b4b2-7b5c003a3189/specs/

**Comment by Deveshshankar** [comment]
Not implementing 
<img width="435" alt="Screenshot 2023-02-16 at 5 55 20 PM" src="https://user-images.githubusercontent.com/107177634/219364214-650cdbc0-f79d-430b-b5ce-9be97a7c85cd.png">
t implementing
