### ISSUE TITLE
List of modules for repo dependencies update

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/bitcointribe#6338]
We need a checklist of items here. This section can be edited and the checklist put here.

- [x] [React](#6152)
- [x] [React Native](#6152)
- [x] React navigation
- [x] [Code cleanup: remove unused modules] (#6749)
     - [ ] Home Dashboard
     - [ ] F&F
     - [ ] BHR
     - [ ] Restore Wallet
     - [ ] Settings
     - [ ] Account
Outcome: All the internal libraries that we're using would be up-to-date.

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
