### ISSUE TITLE
Available balance in test account is zero

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6347]
Not able to test gift scenario as the available balance remains 0 sats
![Screenshot_2023-01-24-18-34-56-87_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/214480903-bb7863a7-d260-491c-8536-29a7cc527adb.jpg)

**Comment by Omkar0803** [comment]
Hey @Deveshshankar, I would like to contribute to this project. Can you tell how can start?

**Comment by Deveshshankar** [comment]
still the balance is zero

**Comment by Deveshshankar** [comment]
Resolved
