### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/bitcointribe#6351]
Step 1:
- [x] Logo redesign
- [x] Main flows color changes
- [x] Opening animation 
- [x] Twitter cover page image
- [x] Twitter profile image
- [ ] Website - Banner image and images of corresponding dimensions, for features mentioned below
- [ ] App/Play store images of Home Screen, Gifts, Settings, Friends and family, Checking Account, Lightning Account, Test Account 
- [ ] An image for announcement to go on Twitter
- [ ] Few images of screens of features/settings etc. we've discarded. Maybe 5 very different screens should be fine. 

Step 2:
- [ ] Color changes for all internal screens
- [ ] Color changes for all Know More screens
- [ ] Loader color changes

**Comment by Pawan2792** [comment]
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/10923254-5498-47b6-9222-d5fa24678f5f/specs/

**Comment by kkartik07** [comment]
@ASN-BitHyve @Pawan2792 can you assign this issue to me? I would like to work on it

**Comment by Pawan2792** [comment]
@summikhan11  please update XD with more new Screens

**Comment by summikhan11** [comment]
App Stores & Google Play
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/0f598bd1-4852-471d-829d-556ba04ebb91/

**Comment by ASN-BitHyve** [comment]
> @ASN-BitHyve can you assign this issue to me? I would like to work on it

Hi @kkartik07. We have a team working on this. Having said would love to know your skillsets. I'm sure we could find something for you all things considered. Please email your portfolio/CV to abhilashn@bithyve.com

**Comment by Deveshshankar** [comment]
Tribe is ready this was related to hexa
