### ISSUE TITLE
Blog on the name change

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/bitcointribe#6352]

**Comment by Omkar0803** [comment]
Hey @ASN-BitHyve , I would like to contribute in this project. Can you guide me how can I start?

**Comment by ASN-BitHyve** [comment]
> Hey @ASN-BitHyve , I would like to contribute in this project. Can you guide me how can I start?

Hey Omkar! Thanks for reaching out. Please send me your CV and cover letter at abhilashn@bithyve.com and we can take it from there.

**Comment by Omkar0803** [comment]
For contributing in this open source project, should I need to submit my CV and cover letter? because it is not an internship or job to provide above things.

**Comment by ASN-BitHyve** [comment]
> For contributing in this open source project, should I need to submit my CV and cover letter? because it is not an internship or job to provide above things.

I could give you specific directions to start if I would know your core strengths and areas of interest :) Thus the ask for a CV and CL. But without knowing these, I can suggest the typical path : 1) Play around with Hexa Wallet. 2) Look at the code. 3) Look at the issues. See what sparks your interest/curiosity and start contributing.

More general directions here: https://opensource.guide/how-to-contribute/ . All the best!

**Comment by Omkar0803** [comment]
> > For contributing in this open source project, should I need to submit my CV and cover letter? because it is not an internship or job to provide above things.
> 
> I could give you specific directions to start if I would know your core strengths and areas of interest :) Thus the ask for a CV and CL. But without knowing these, I can suggest the typical path : 1) Play around with Hexa Wallet. 2) Look at the code. 3) Look at the issues. See what sparks your interest/curiosity and start contributing.
> 
> More general directions here: https://opensource.guide/how-to-contribute/ . All the best!

wd

**Comment by Omkar0803** [comment]
A very thank @ASN-BitHyve for guiding me, I just misunderstand that thing, yes your totally right about CV and CL. I will start working on hexa wallet as you suggested me. Here are my [CV](https://drive.google.com/file/d/1UkHUbX3cfjgXFPTvUyJna5BN990DK4kW/view?usp=share_link) 
and [portfolio](https://www.omkardarde.me/) 

Thanks you @ASN-BitHyve

**Comment by ASN-BitHyve** [comment]
> A very thank @ASN-BitHyve for guiding me, I just misunderstand that thing, yes your totally right about CV and CL. I will start working on hexa wallet as you suggested me. Here are my [CV](https://drive.google.com/file/d/1UkHUbX3cfjgXFPTvUyJna5BN990DK4kW/view?usp=share_link) and [portfolio](https://www.omkardarde.me/)
> 
> Thanks you @ASN-BitHyve

Now that I know that your interest lies in front end development, I can suggest the following. Download the android version of Hexa wallet from the Playstore. Right from the opening animation, observe everything... the loading times response times, messages that you see, your experience on the home page, the test account, etc. Log your observations and share them with me on my TG: @AbhilashNair11 . We'll take it from there :)

**Comment by Kali-Decoder** [comment]
Is there any hexa wallet social group for communication please add me @ASN-BitHyve

**Comment by ASN-BitHyve** [comment]
> Is there any hexa wallet social group for communication please add me @ASN-BitHyve 

https://t.me/HexaWallet There you go 😊
