### ISSUE TITLE
Need to change Colour of asset and Small animation

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6357]
For example 
App login 
Creating passcode 
On gift Screen 
On F&F Screen
On modal 
![Screenshot_2023-02-13-11-54-12-10_6ccb4bf936ab2cedd5e025652c6047ae (1)](https://user-images.githubusercontent.com/107177634/218388941-24ffadd1-f0e3-4080-bc60-9fe57533a29e.jpg)
![Screenshot_2023-02-13-11-53-36-28_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/218388965-de706154-14a1-42e5-a535-42b8df4d3845.jpg)
![Screenshot_2023-02-13-12-20-24-17_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/218390314-0e4d71b8-70d7-4426-ba18-7c829fe4fa4f.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/2689c545-661c-46e5-bfd0-9ae3f56a0106/

let me know if i've missed any illustrations @Deveshshankar

**Comment by Deveshshankar** [comment]
resolved 2.1.4(545)
