### ISSUE TITLE
Icon in QR image 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6372]
For eg 
![IMG_5389](https://user-images.githubusercontent.com/107177634/218682632-128a4ac0-a7ac-4127-8500-5859315535d0.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/c1e1e673-c902-4e16-b11c-ec8d609ac716/

**Comment by Deveshshankar** [comment]
fixed
