### ISSUE TITLE
Assets for QR center image logo

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/bitcointribe#6374]
![Simulator Screen Shot - iPhone 11 - 2023-02-14 at 16 21 22](https://user-images.githubusercontent.com/99478432/218714663-510b1274-7f01-433f-a956-34bc0fe62b3b.png)
![Simulator Screen Shot - iPhone 11 - 2023-02-14 at 16 41 16](https://user-images.githubusercontent.com/99478432/218733342-d37f0f2c-bfe2-4197-b5ff-427bc1199a95.png)

![Simulator Screen Shot - iPhone 11 - 2023-02-14 at 16 45 43](https://user-images.githubusercontent.com/99478432/218733348-ca4b689d-e4bf-422e-8f27-7c8756246261.png)
![Simulator Screen Shot - iPhone 11 - 2023-02-14 at 16 49 05](https://user-images.githubusercontent.com/99478432/218733352-d8c45ec1-c4a9-486d-9a30-7d8a5fdd4021.png)
![Simulator Screen Sho
![Simulator Screen Shot - iPhone 11 - 2023-02-14 at 18 19 46](https://user-images.githubusercontent.com/99478432/218744156-5ee8b92d-7cd7-4557-9611-21eae52026e1.png)
t - iPhone 11 - 2023-02-14 at 17 25 38](https://user-images.githubusercontent.com/99478432/218733356-cb0353d1-4e00-49e8-a5d2-4d20ce93dad7.png)

![Simulator Screen Shot - iPhone 11 - 2023-02-14 at 22 27 30](https://user-images.githubusercontent.com/99478432/218805368-be0d3f80-c70d-44ac-a8c0-b2cf05799135.png)

![Simulator Screen Shot - iPhone 11 - 2023-02-14 at 18 35 58](https://user-images.githubusercontent.com/99478432/218805644-f5140673-f3f5-4101-85db-e8b1c3478a65.png)

**Comment by Deveshshankar** [comment]
@Pawan2792 remove shadow in CTA (Download Bitcoin Keeper)

**Comment by Deveshshankar** [comment]
fixed
