### ISSUE TITLE
Need Icon

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6384]
![simulator_screenshot_7D5F88FC-2474-4269-A7CE-2E2FE404A3DC](https://user-images.githubusercontent.com/107177634/218982257-2935f44d-68a8-4a77-a046-2b00fa903e88.png)
![simulator_screenshot_1447D1D0-B3F9-42B6-B375-9EB3EC0D47B1](https://user-images.githubusercontent.com/107177634/218982271-fcf35c10-b477-4812-96ae-262f81b8095c.png)
![simulator_screenshot_EF29EFE7-021F-46B8-B443-79BE255281B5](https://user-images.githubusercontent.com/107177634/218982290-48d783ef-269d-454a-900e-fefa47a1cf12.png)
![simulator_screenshot_1ED12DFD-5A6D-4ABF-BEE3-455F0E5C3E91](https://user-images.githubusercontent.com/107177634/218982308-3dcc687a-e328-489e-936a-198f06988d59.png)
![Screenshot_1676451623](https://user-images.githubusercontent.com/107177634/218982708-4743fc82-62cf-4d77-b2e3-c5576efef6ce.png)

**Comment by summikhan11** [comment]
Scroll to find all
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/56934c3e-375f-42a5-b609-84ff6415dc76/
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/352dbf6b-a7e2-49a0-a1a6-d85595415db3/

**Comment by Deveshshankar** [comment]
Fixed
