### ISSUE TITLE
Need asset /icon

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6393]
![IMG_5421 2](https://user-images.githubusercontent.com/107177634/219298983-2ea0db83-3ce0-4931-90e4-f8ec996fa41c.jpg)

![Screenshot_2023-02-16-09-57-38-99_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/219301378-be892491-c835-4f1d-b5d9-909d9d0382a5.jpg)

![IMG_5419](https://user-images.githubusercontent.com/107177634/219301547-3b46ab6e-0dd0-4158-af8e-90c4f4a1d0c0.jpg)

**Comment by Pawan2792** [comment]
@summikhan11 
please update Xd with above Assets.

**Comment by summikhan11** [comment]
1. https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/02c591e5-c117-441f-9f3e-f689bf7fc8c3/

2. this is just a color setting , im assuming you dont need a svg for this

3. https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/1ff7f2e3-c89a-4ddb-85aa-a95ef23877c8/specs/

4. https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/2689c545-661c-46e5-bfd0-9ae3f56a0106/specs/

**Comment by Deveshshankar** [comment]
Fixed
