### ISSUE TITLE
alignment on buy bitcoin

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6394]
![IMG_5420](https://user-images.githubusercontent.com/107177634/219295279-85f6a5fa-77a4-4a6c-acda-2e67cc10aea2.jpg)

**Comment by yatharthagoenka** [comment]
Hi, 
Could you please mention the expected behaviour and whether the issue is open for assignment?

**Comment by Deveshshankar** [comment]
Fixed
