### ISSUE TITLE
Toast message design across the app 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6397]
Use this 
<img width="256" alt="Screenshot 2023-02-16 at 4 35 35 PM" src="https://user-images.githubusercontent.com/107177634/219348315-145bf10c-49b1-4eed-bef4-04d6f39a7dab.png">

**Comment by Deveshshankar** [comment]
1.Can't see changes in iOS 
2. In android size of box is bigger plz refer design @cakesoft-neha

**Comment by cakesoft-swati** [comment]
![Screenshot_2023-10-10-11-14-21-46_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/aea0541f-9e4d-44b7-bad5-de1c0194ce53)
- Toast messages are still not proper.All the things are overlapping.
- Tested in Tribe app v 2.3.0(619)

**Comment by cakesoft-neha** [comment]
This seems to be a device specific issue, I checked this issue on Tribe app v2.3.0.
I think these black toast messages generated from a device.
  
![WhatsApp Image 2023-10-12 at 12 26 59 PM](https://github.com/bithyve/bitcointribe/assets/62868075/2cf49581-3dc7-425d-a048-b1f5c44c4f23)

**Comment by Deveshshankar** [comment]
Not as per design

**Comment by Deveshshankar** [comment]
Duplicate
