### ISSUE TITLE
Swan Bitcoin

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6406]
1. Alignment at the top  **Resolved**
2. Cross button not working **Resolved**
3. moving here and there unable to perform the task user wants.
![IMG_20230220_153330](https://user-images.githubusercontent.com/107177634/220075786-f83e91ed-c3c3-49a1-a773-86f580176b72.jpg)

https://user-images.githubusercontent.com/107177634/228511703-054b155c-9cd6-489f-85a8-f392492481b5.MP4

**Comment by Deveshshankar** [comment]
Have to check on ios build

**Comment by Deveshshankar** [comment]
Check this for reference 
https://user-images.githubusercontent.com/107177634/228511381-ab6869ea-119d-4e0a-aa75-4e042602ac82.MP4

**Comment by Pawan2792** [comment]
@Deveshshankar  Please check in build 554

**Comment by Deveshshankar** [comment]
@Pawan2792  getting this ![IMG_AEBFFB4DF6E0-1](https://user-images.githubusercontent.com/107177634/229995603-693018d9-7129-48a1-964e-7e79e277d9b2.jpeg)

**Comment by Pawan2792** [comment]
it will work in Live mode @Deveshshankar
