### ISSUE TITLE
Github Home Website URL not reachable

### ISSUE THREAD

**Issue by SiddheshKukade** [bithyve/bitcointribe#6434]
Dear admin ,
I've come across this from the summer of bitcoin website as I am interested in participating as a contributor.

## Problem : 
![image](https://user-images.githubusercontent.com/65951872/224101365-30e1944d-8489-420b-b4d0-3af02fbe7102.png)

### The link for https://bitcointribe.app/ is not working and gives this error.
![image](https://user-images.githubusercontent.com/65951872/224101622-50bea5fd-8a02-4bab-bbdc-75146608900b.png)

**Comment by cakesoft-shashank** [comment]
Please use hexawallet.io for now. Our new website will be up in a few days
