### ISSUE TITLE
Missing .`env.examples` 

### ISSUE THREAD

**Issue by Abhijay007** [bithyve/bitcointribe#6435]
The `.env.example` file is not present in the repo, The file essential for Configuring Environment Variables for the Mainnet and  Testnet, but the `.env` file and `.env.example` files are not present in the repo as those files are mentioned in `.gitignore` so it might not be staged, add those files or please add details related to those files in the `readme.md` as future contributors might not able to run the project locally without that.

**Comment by cakesoft-shashank** [comment]
Please refer [HexaConfig.ts)](https://github.com/bithyve/bitcointribe/blob/development/src/bitcoin/HexaConfig.ts), even if you don't add .env it should pick testnet env
