### ISSUE TITLE
Change old logo and icon on  buy bitcoin page

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6436]
On the buy bitcoin page name and logo are old 
![Image from iOS (8)](https://user-images.githubusercontent.com/107177634/224469825-4ef88dde-4c8a-4b58-933f-75146b6bf561.jpg)

**Comment by AnmolSirola** [comment]
@Deveshshankar Can I work on this issue ?

**Comment by arishmaurya** [comment]
@Deveshshankar can you please explain it more i want to work on this issue and kindly provide some setup guide

**Comment by Deveshshankar** [comment]
Resolved
