### ISSUE TITLE
Need to update Bitcoin Tribe Feature Graphic on stores 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6437]
<img width="442" alt="Screenshot 2023-03-13 at 11 51 08 AM" src="https://user-images.githubusercontent.com/107177634/224623437-a2c7e62f-bf8f-4e25-8189-aac4c58547bb.png">

**Comment by cakesoft-shashank** [comment]
Feature graphic updated on playstore
