### ISSUE TITLE
Issue in setting up the project. - Unable to find .env.example

### ISSUE THREAD

**Issue by asaikarthikeya** [bithyve/bitcointribe#6438]
Hi. I have been trying to set up the project in my Ubantu machine as per the Readme.

when i try to set up the Environment Variables(https://github.com/bithyve/bitcointribe#configuring-environment-variables), i am getting an error message as no such file called as .env.example.

![Screenshot from 2023-03-20 00-36-55](https://user-images.githubusercontent.com/70392921/226203371-295b77e8-35c3-4727-912b-d5f759d8e2c5.png)

**Comment by asaikarthikeya** [comment]
@Pawan2792 @cakesoft-shashank @Deveshshankar. It would mean a lot if anyone could help me with this. Thanks :)

**Comment by Pawan2792** [comment]
@asaikarthikeya  .env is not required to run/build dev app. you can run the app without.env, code will automatically pick dev environment.

**Comment by asaikarthikeya** [comment]
Hi @Pawan2792 , I think the setup documentation need more update. 

I see that `setup.sh` is not automatically created after `yarn install` as mentioned [here](https://github.com/bithyve/bitcointribe#running-setup-script), I had to run  these commands to create `setup.sh`

1. chmod +x setup.sh 
2. sh ./setup.sh

**Comment by asaikarthikeya** [comment]
> Hi @Pawan2792 , I think the setup documentation need more update.
> 
> I see that `setup.sh` is not automatically created after `yarn install` as mentioned [here](https://github.com/bithyve/bitcointribe#running-setup-script), I had to run these commands to create `setup.sh`
> 
> 1. chmod +x setup.sh
> 2. sh ./setup.sh

Ah, Looks like this has not resolved the error. Error message of `setup.sh`  can be seen in the above SS.

**Comment by asaikarthikeya** [comment]
Looks like `.env` file is required to run the project. Hopefully this gets resolved by [this commit](https://github.com/bithyve/bitcointribe/pull/6441/commits/9e10bf8a63f8d3b86b436026eda03842bc10828e) of your lastest PR?
![Screenshot from 2023-03-22 23-12-35](https://user-images.githubusercontent.com/70392921/226994375-31203d6b-1172-40d2-92c2-e0ce601c777d.png)

**Comment by asaikarthikeya** [comment]
Error as - A problem occurred configuring project ':app'.
> Could not create task ':app:lintDevelopmentDebug'. 

Regarding the environment variable error, I have set up the Android envi, conformed by running  `echo $ANDROID_HOME
`. Not sure why this still exists. Searched and tried many ways but unfortunately  i am unable to resolve this :(  

![Screenshot from 2023-03-23 00-07-22](https://user-images.githubusercontent.com/70392921/227010569-931b2d31-7c6d-44f7-96c2-3e2ffa914dd4.png)

**Comment by Praasd** [comment]
@Pawan2792  is this issue closed?

**Comment by Pawan2792** [comment]
@asaikarthikeya any update on android development env setup ?

**Comment by asaikarthikeya** [comment]
@Pawan2792 if possible, could we connect? I have sent you the updates on slack. I was waiting for your response their. Thank you

**Comment by Pawan2792** [comment]
@asaikarthikeya please complete basic setup of your system android studio & react native environment setup in you Ubuntu system & ping me on slack.

**Comment by utkrishta24** [comment]
@Pawan2792 I am unable to run bitcoin tribe in my system, i have setup physical device as emulator, setup android studio and react native environment. Yarn install and yarn android or npm install both are giving errors. please help.

**Comment by asaikarthikeya** [comment]
> @Pawan2792 I am unable to run bitcoin tribe in my system, i have setup physical device as emulator, setup android studio and react native environment. Yarn install and yarn android or npm install both are giving errors. please help.

Yes Same with me. I have also setup everything but issues continue to exist. Seems like the issues are due to gradle version and gradle plug-in version. @Pawan2792 Could you please suggest me the version on which the app is working for you? Thank you

**Comment by asaikarthikeya** [comment]
So here is the update regarding this issue - 

Instead of `yarn android` mentioned in Readme, if i use  `react-native run-android --variant developmentDebug` or `yarn android  --variant developmentDebug`. the apps starts to run but does not respond. 

![Screenshot from 2023-04-25 20-02-40](https://user-images.githubusercontent.com/70392921/234310333-1c743093-735f-4657-adcf-325418f9e419.png)

tried `adb reverse tcp:8081 tcp:8081` in android folder as mentioned by @Pawan2792. 

After I enter a random passcode, app is not responding.(Attached screen recording below)



https://user-images.githubusercontent.com/70392921/234311591-245e299c-1a83-45d9-be14-e6a953ea8306.mp4

**Comment by Deveshshankar** [comment]
not as per plan
