### ISSUE TITLE
Instalation: Yarn install does not work

### ISSUE THREAD

**Issue by vasvi-sood** [bithyve/bitcointribe#6452]
<img width="403" alt="Screenshot 2023-04-09 at 1 21 12 PM" src="https://user-images.githubusercontent.com/76619050/230761187-bbc4cd61-42da-4e5a-94dc-43424604961b.png">

**Comment by vasvi-sood** [comment]
Kindly assign this issue to me

**Comment by cakesoft-shashank** [comment]
Install [yarn](https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable) or try with `npm install`
