### ISSUE TITLE
Product> Build for> Running giving an error

### ISSUE THREAD

**Issue by vasvi-sood** [bithyve/bitcointribe#6454]
<img width="822" alt="Screenshot 2023-04-09 at 2 16 44 PM" src="https://user-images.githubusercontent.com/76619050/230763286-0723cdfb-36f2-4ee7-9626-a2b86d0c47bc.png">
Steps to reproduce on MacOS:
<ol>
<li> Clone the repo</li>
<li>cd bitcointribe</li>
<li>yarn install</li>
<li>Open HEXA.xcworkspace from <Hexa Project Root>/iOS in XCode and use the product > build for > running

**Comment by cakesoft-shashank** [comment]
Whats your xcode version?

**Comment by vasvi-sood** [comment]
@cakesoft-shashank version: 14.2.0.0.1.1668646533

**Comment by Deveshshankar** [comment]
Closing Cc @cakesoft-shashank
