### ISSUE TITLE
Main Website not working

### ISSUE THREAD

**Issue by Aakash231217** [bithyve/bitcointribe#6459]
You can check out the website you have given on the link , currently it's not opening, there might be some issue or the website has moved to new URL

**Comment by Deveshshankar** [comment]
@Aakash231217 are you talking about Hexa or Tribe?
https://hexawallet.io/#contact

**Comment by Aakash231217** [comment]
Tribe

**Comment by Deveshshankar** [comment]
@Aakash231217 As per my knowledge we haven't done Tribe web live yet. Where did you find the link you are talking about let me know so I can help you.

**Comment by mohitvdx** [comment]
which website? send link

**Comment by Aakash231217** [comment]
The one which is on github
