### ISSUE TITLE
Add Text on the Scan QR Screen during Create with Keeper flow 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/bitcointribe#6483]
To scan QR:
Open the Keeper App > Go to Linked Wallets >  Select Wallet Seed Words > Enter your Keeper passcode > There beneath the hidden Seed Words click on Show as QR. Please scan that QR

**Comment by Pawan2792** [comment]
@summikhan11  can you please suggest better way to present information text in below screen
cc: @ASN-BitHyve  
![Simulator Screen Shot - iPhone 13 - 2023-04-25 at 12 35 56](https://user-images.githubusercontent.com/99478432/234292693-896fce89-ba6a-44c2-8d34-1877c952ae64.png)

**Comment by Deveshshankar** [comment]
Completed
