### ISSUE TITLE
Need an Upload from Gallery button for Create with Keeper flow

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/bitcointribe#6484]
Beneath the camera window, we need the Upload from Gallery button like we have in Keeper.

**Comment by akshay8551** [comment]
Resolved,

<img width="328" alt="Screenshot 2024-02-12 at 10 45 56 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/5861d13a-89f4-4855-a269-3d4644f0042c">

**Comment by Deveshshankar** [comment]
Completed
