### ISSUE TITLE
Import wallet Keeper side alignment 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6488]
Text cutting at side Device Galaxy F25 5G dev App

![Screenshot_20230425_160134_Keeper](https://user-images.githubusercontent.com/107177634/234258580-e1fd77cd-aac3-4a68-a7bb-edaf265c3c20.jpg)

**Comment by cakesoft-swati** [comment]
- Still having the same issue in keeper app v 1.0.3(158)

**Comment by Deveshshankar** [comment]
![IMG_6055](https://github.com/bithyve/bitcointribe/assets/107177634/e4d878b7-e69e-437d-8ba5-29098712e0fc)
not resolved @Pawan2792

**Comment by Deveshshankar** [comment]
Completed
