### ISSUE TITLE
Backup with Keeper:App behaviour is weird on this screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6494]
https://user-images.githubusercontent.com/62699947/234780678-e15289cf-50ce-40a2-8f18-91c43c674d83.mp4
- After passing this screen I am not be able to kill the app.Tribe or Keeper app is also not reacting properly even after several attempts to kill.

**Comment by Deveshshankar** [comment]
Not relevant
