### ISSUE TITLE
Text change when wallet has been backed up with Keeper

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/bitcointribe#6502]
If the wallet has been created using Keeper or when the user is done backing up the wallet with Keeper, the message should be:

" Your wallet is backed up with Keeper"
![photo_6223986071440570282_y](https://user-images.githubusercontent.com/68264080/235151948-15f20238-f6ad-4d0a-8f21-cd68735998c1.jpg)

**Comment by Deveshshankar** [comment]
Resolved in 2.1.7 (566)
