### ISSUE TITLE
We are Using "Backup Phrase" 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6503]
We are Using a "Backup Phrase" Seed word or word is not correct here 
![IMG_5644](https://user-images.githubusercontent.com/107177634/235151919-0f73f333-f5cb-45bf-968d-fe32c42a6b4d.jpg)
![IMG_5645](https://user-images.githubusercontent.com/107177634/235151944-ab58f4da-f6fe-4e3d-9810-af6120acb69f.jpg)

**Comment by cakesoft-swati** [comment]
![Screenshot_2023-05-05-11-05-29-51_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/62699947/236384180-c1069cf0-e225-4a12-9d6e-f17b15ebac0e.jpg)
- Text is cutting here.Tested in Tribe app v 2.1.5(562)

**Comment by Deveshshankar** [comment]
Resolved in 2.1.6(563)
