### ISSUE TITLE
It keeps on loading "available to spend sats is not appearing 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6505]
![IMG_5649](https://user-images.githubusercontent.com/107177634/235153316-c8c23f56-73e0-4e87-919e-fd762949fca2.PNG)

**Comment by Pawan2792** [comment]
@Deveshshankar  it working fine at my end

**Comment by Deveshshankar** [comment]
It Did at my end as well but have to go inside the test account and refresh it and wait the it reflects could be more smooth. Closing for now
