### ISSUE TITLE
Backup flow from the home screen

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/bitcointribe#6507]
When the user clicks on Confirm Backup Phrase on the home screen highlight section, he should be taken to the latest wallet backup section that shows both the methods of backing up. Currently, its only showing one method.

**Comment by cakesoft-swati** [comment]
- still having the same issue in tribe app v 2.1.5(562)

**Comment by Deveshshankar** [comment]
Resolved in 2.1.7 (566) dev app
