### ISSUE TITLE
Textual changes 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6508]
<img width="179" alt="Screenshot 2023-05-02 at 12 56 34 PM" src="https://user-images.githubusercontent.com/107177634/235635045-5a7d1449-0e99-402f-a4de-70f893d4c868.png">

**Comment by Pawan2792** [comment]
![Simulator Screen Shot - iPhone 13 - 2023-05-02 at 18 50 25](https://user-images.githubusercontent.com/99478432/235838842-6ab9b010-9e6c-475a-b20c-9b27a2aa0bab.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.1.5(562)
