### ISSUE TITLE
Optimising backup with Keeper option

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/bitcointribe#6515]
This QR can be scanned on Hexa when the user choses "backup with Keeper" on the first screen and chooses scan QR.
Also the user can choose to deeplink from this screen which needs to fetch the BIP-85 wallet seed from Keeper. The user selects a particular wallet whose seed is used for creating Keeper.

![Simulator Screen Shot - iPhone 13 - 2023-05-05 at 12 07 27](https://user-images.githubusercontent.com/99478432/236391600-d2db2b57-63f1-4b65-8f1f-ad6278ae57c0.png)

**Comment by Deveshshankar** [comment]
@summikhan11 Description added to the issue

**Comment by Deveshshankar** [comment]
Duplicate issue
