### ISSUE TITLE
Tribe Home Screen 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6527]
1. No gradient at the top 
2. The account Tile's colour is white and the colour in the background is not white 

<img width="439" alt="Screenshot 2023-05-09 at 5 20 00 PM" src="https://github.com/bithyve/bitcointribe/assets/107177634/b2dafaa0-fa77-4a46-9703-8bba5f3f8bd6">

**Comment by cakesoft-neha** [comment]
Fixed in 8bc9277631754188085520f44da4f1ab82cdfa7c

**Comment by Deveshshankar** [comment]
Completed 2.3.0(616)
