### ISSUE TITLE
UI Changes gift inner screen 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6531]
![IMG_5702](https://github.com/bithyve/bitcointribe/assets/107177634/53a92456-173a-42a8-8c81-f982a0724946)

**Comment by akshay8551** [comment]
Fixed,

![simulator_screenshot_3C42B4D0-37BA-41F6-A360-A76583795585](https://github.com/bithyve/bitcointribe/assets/61345820/b0a761f5-5545-4745-a241-e48c58fc59ee)

**Comment by Deveshshankar** [comment]
Completed
