### ISSUE TITLE
Backup + Recovery 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6535]
1. The Sequence should be the same in both cases 
2. When the user enters the first Phrase correctly the pointer should go on 2nd automatically user should not have to select manually

<img width="430" alt="Screenshot 2023-05-10 at 11 50 46 AM" src="https://github.com/bithyve/bitcointribe/assets/107177634/c0ec7201-f75f-4d28-9727-80b1b81f8db9">

**Comment by cakesoft-swati** [comment]
- Still the sequence is not same in both cases backup and recovery.
- Tested on Tribe app v 2.2.4(599)

**Comment by cakesoft-neha** [comment]
Fixed in 8af4d92e11cdd9e2a953e5884c11b4af1e7486fe[](url)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(616)
