### ISSUE TITLE
Camera “Permission denied"

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6546]
If the user denied the Permission it is very difficult to allow 
Refer the way we had done in keeper 
![Screenshot_2023-05-15-18-09-50-06_e03f8efe4e3aa3499c333ec322d918e3](https://github.com/bithyve/bitcointribe/assets/107177634/e6b43989-5084-40a6-9eaf-ad85ff28075e)

**Comment by Deveshshankar** [comment]
not resolved in 2.3.0 (619) iOS

**Comment by Deveshshankar** [comment]
not resolved in 2.3.0 (619) iOS

**Comment by cakesoft-swati** [comment]
- Verified this issue in Tribe app v 2.3.0(619)
