### ISSUE TITLE
Gift Link preview 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6549]
The link preview is not correct 

https://gift.bitcointribe.app/FhH37FtNtadx8gL97
<img width="595" alt="Screenshot 2023-05-16 at 12 47 42 PM" src="https://github.com/bithyve/bitcoin-keeper/assets/107177634/47b2b67f-3d91-45d0-a040-3381acc4930f">

**Comment by cakesoft-shashank** [comment]
Ref: https://github.com/firebase/firebase-ios-sdk/issues/5333

**Comment by Deveshshankar** [comment]
Not as per plan
