### ISSUE TITLE
Recover Existing Wallet:Test script

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6551]
- Test scripts for wallet recovery flow which will include:
1.Using Backup Phrase flow
2.Using Recovery Keys flow.

**Comment by Deveshshankar** [comment]
Closing CC @cakesoft-swati

**Comment by cakesoft-shashank** [comment]
Irrelevant

**Comment by Deveshshankar** [comment]
Closing CC @cakesoft-shashank
