### ISSUE TITLE
Sync RGB assets

### ISSUE THREAD

**Issue by cakesoft-shashank** [bithyve/bitcointribe#6556]
1. Sync RGB20 (Collectibles) and RGB121 (Coins) assets 
2. Implement pull to refresh on RGB screen.
3. UI Link: https://xd.adobe.com/view/513aecc1-ec34-4259-bf3e-956ddb5b60f3-0469/screen/5758c582-ee24-4716-8083-ecc65031fa0c

These changes are required on both
- [ ] Android
- [ ] iOS

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(616)
