### ISSUE TITLE
Website and  domain related changes.

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6578]
Currently, it is redirected to the Hexa web 
Use this link https://bitcointribe.app/terms-of-service/
![IMG_8021](https://github.com/bithyve/bitcointribe/assets/107177634/ad9ae4e2-9587-4a4a-8fbc-8b5a08c9cc10)

- Change dynamic links from hexawallet.io to bitcointribe.app

**Comment by Deveshshankar** [comment]
fixed

**Comment by cakesoft-neha** [comment]
Fixed and raised PR fe08aab370c519c4257656c7578df9f35facc411[](url)

**Comment by Deveshshankar** [comment]
Completed
