### ISSUE TITLE
Gift creation fails. 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6587]
1.Not as per design colour and fonts looks very different
2. Inner screen needs to be updated as per design
3.Single or Multiple Gift creation fails 
Dev screen 
![img_6005](https://github.com/bithyve/bitcointribe/assets/107177634/094371dd-1572-4336-b7fb-35bf0bef5d84)
![img_6006](https://github.com/bithyve/bitcointribe/assets/107177634/e5b447c7-ed4b-4f5c-a73a-1e5ace0a8bde)
Design Screen 
![Screenshot_2023-07-12-15-31-58-69_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/bithyve/bitcointribe/assets/107177634/aa5f6ffc-3af7-4b3a-a785-7ec3cb196bfb)

**Comment by GauravDhak** [comment]
hey Pawan , I hope this message finds you well. I am reaching out to you regarding this issue I would like to Work  in this issue if you want to any help feel free to connect me

**Comment by Deveshshankar** [comment]
Completed
