### ISSUE TITLE
RGB need UX consideration 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6595]
1.Done

<img width="127" alt="Screenshot 2023-08-28 at 2 31 38 PM" src="https://github.com/bithyve/bitcointribe/assets/107177634/587a2057-d3b3-4220-a3f8-197dee7ef513">

2. Need a scanner in send Flow

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/513aecc1-ec34-4259-bf3e-956ddb5b60f3-0469/screen/51abb76e-95fe-4519-847c-9aa5e66f2b3f/

**Comment by cakesoft-swati** [comment]
- Verified this issue in Tribe app v 2.3.0(619)
