### ISSUE TITLE
Send screen:Text is getting cut off on the send screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6599]
![File (3)](https://github.com/bithyve/bitcointribe/assets/62699947/b79f5fd8-26f4-4d5a-9e57-819f557dd38c)

It should not be sending from Saving account 
![IMG_6046](https://github.com/bithyve/bitcointribe/assets/107177634/4cc8795e-5ffc-4163-84c7-98a93a234b00)

**Comment by Deveshshankar** [comment]
Did not get iOS release

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(619)
