### ISSUE TITLE
RGB - Introduction modal

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6604]
We can also have a loading modal for RGB
“Introducing RGB assets”
Now Issue, receive, send and sync assets with your tribe
Ideally we should have the RGB logo there

**Comment by Deveshshankar** [comment]
<img width="173" alt="Screenshot 2024-02-13 at 11 24 41 AM" src="https://github.com/bithyve/bitcointribe/assets/107177634/a7d7d63a-b73c-418c-8402-c698c3317801">

**Comment by Deveshshankar** [comment]
https://xd.adobe.com/view/2af996b7-0e6e-453b-9c82-c735e28a43e7-7faa/specs/

**Comment by akshay8551** [comment]
Done.

https://github.com/bithyve/bitcointribe/assets/61345820/09cbbbaf-c86e-4b12-8562-1b1c91796652

https://github.com/bithyve/bitcointribe/assets/61345820/764fa8fd-61fd-42fe-8db2-346a0f7ea418

**Comment by Deveshshankar** [comment]
Completed
