### ISSUE TITLE
Remove RGB in adding LN account flow

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6610]
Remove RGB in adding LN account flow
This is from the old flow. Need to take it out to keep only LN. For RGB we have a Tab on Home screen.

https://github.com/bithyve/bitcointribe/assets/107177634/636dd5d6-dd92-4a33-b6f8-b2e67c175d63

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(616)
