### ISSUE TITLE
User reported issue

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/bitcointribe#6616]
Hi guys! Found some coin on my Hexa legacy wallet, but im unable to send transaction. It says insufficient balance, even though the amount should be ok. Also I'm unable to generate a backup, as the app crashes when tapping on  manage your wallet backup. What could be a solution, could I locate the private keyson my phone?
Wallet version is 1.7.9
![IMG_20230724_115942_517](https://github.com/bithyve/bitcointribe/assets/99478432/1551c8b1-70b7-43b5-94ee-8b865593c720)

**Comment by Deveshshankar** [comment]
Closing cc @ASN-BitHyve
