### ISSUE TITLE
Border wallet:UI issue

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6625]
![Screenshot_2023-08-10-15-04-27-00_abb9c8060a0a12c5ac89e934e52a2f4f](https://github.com/bithyve/bitcointribe/assets/62699947/c884aa8a-7619-454a-bee9-8366897a358c)
- Pattern should not be scrollable.

![Screenshot_2023-08-10-15-04-38-99_abb9c8060a0a12c5ac89e934e52a2f4f](https://github.com/bithyve/bitcointribe/assets/62699947/616b623c-9eef-4e7a-867c-7996e6f33939)
- 'Continue' button is cutting from bottom.

**Comment by akshay8551** [comment]
Resolved,
![simulator_screenshot_C7BF8B94-69FC-4183-92E1-96E3A7971D2C](https://github.com/bithyve/bitcointribe/assets/61345820/c9d4739c-da00-4f77-bdcd-8ef2a83b706a)

**Comment by Deveshshankar** [comment]
resolved
