### ISSUE TITLE
Wallet Backup 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6626]
All three to be shown with the ones not used as just an option (no orange mark) and the one used with a tick
Wallet Backup Phrase
Backup with Keeper
Border Wallet
![IMG_8352](https://github.com/bithyve/bitcoin-keeper/assets/107177634/7c07a74a-0a89-4f04-be07-a4f13bdb0aac)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e7fe32c6-047a-42b3-b3fe-fe92b4d9e11b-b2ad/screen/c40859de-6fee-4128-ac38-a0af82e71ec9/

**Comment by akshay8551** [comment]
Resolved

![simulator_screenshot_BF125E28-C73A-4BF3-BDF2-D1C4D3CD0CAD](https://github.com/bithyve/bitcointribe/assets/61345820/1e4b57f9-874d-49b7-aebf-696d8e7bd66c)

![simulator_screenshot_0CA251CB-DD85-4B54-BCCA-86E94983E1D2](https://github.com/bithyve/bitcointribe/assets/61345820/bb623fc2-c5cf-4451-9b3b-ac5c63d4abd5)

**Comment by Deveshshankar** [comment]
Completed
