### ISSUE TITLE
Grid selection 12th word

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6627]
Some toast or a message when user tries to select the 12th word here
![IMG_8347](https://github.com/bithyve/bitcointribe/assets/107177634/b8dbfb79-ebd6-4f20-8c6e-4c3c0e263f6b)

**Comment by akshay8551** [comment]
Resolved,

<img width="327" alt="Screenshot 2023-08-14 at 10 27 06 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/a1d114ea-dd75-4df4-b601-40f2f48b05ce">

**Comment by Deveshshankar** [comment]
resolved
