### ISSUE TITLE
Backup / Recovery Numbering 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6629]
The backup list and recovery should be in same numbering 
![IMG_8348](https://github.com/bithyve/bitcointribe/assets/107177634/efb459f7-9c20-4878-94b0-1c09b576150a)

![IMG_8356](https://github.com/bithyve/bitcointribe/assets/107177634/e54fc867-715d-4af2-b3a7-84017025258b)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.4(597)
