### ISSUE TITLE
White line on the grid 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6637]
![image.png](https://github.com/bithyve/bitcointribe/assets/107177634/d32b634b-f10b-4b9f-824b-0afd64816346)

**Comment by akshay8551** [comment]
Resolved,
<img width="327" alt="Screenshot 2023-08-14 at 10 17 45 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/7be04684-ed3d-4889-82d7-01cabc8bf29f">

**Comment by Deveshshankar** [comment]
resolved
