### ISSUE TITLE
CTA does not respond

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6639]
1. CTA does not respond
2. Position of "Start Again"
<img width="270" alt="Screenshot 2023-08-14 at 1 38 00 PM" src="https://github.com/bithyve/bitcointribe/assets/107177634/2b4f8111-86cc-4de9-a3ff-f35ffb800ee7">

**Comment by akshay8551** [comment]
Resolved
![simulator_screenshot_696AF554-D9AF-43E2-97FE-40597C10550D](https://github.com/bithyve/bitcointribe/assets/61345820/81b6b9de-6c92-4dd6-949b-458843f25820)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.4(597)
