### ISSUE TITLE
Preview pattern 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6641]
Show word on the preview page also
<img width="259" alt="Screenshot 2023-08-14 at 1 55 15 PM" src="https://github.com/bithyve/bitcointribe/assets/107177634/b687338c-55d6-40c9-9190-8d20a9a4c31c">

**Comment by cakesoft-shashank** [comment]
Irrelevant issue. We are showing sequence in the preview not words

**Comment by Deveshshankar** [comment]
CC @cakesoft-shashank Closing
