### ISSUE TITLE
Backup was done but not reflecting at top

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6652]
![screenshot_2023-08-16-10-32-45-44_20dc81889e0fe9e2ef2bddb793fc77ef_720](https://github.com/bithyve/bitcointribe/assets/107177634/c4acd572-abf8-4166-806c-047b7a886915)

**Comment by akshay8551** [comment]
Resolved,

![simulator_screenshot_D367667B-4E67-4032-BB76-1020BDE625CE](https://github.com/bithyve/bitcointribe/assets/61345820/e56357ac-8fba-4511-937c-22334cba48f9)

**Comment by Deveshshankar** [comment]
Unable to do backup due to blank grid

**Comment by Deveshshankar** [comment]
Completed
