### ISSUE TITLE
Restore Boarder wallet 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6653]
User recovered a Boarder wallet but It shows Seed backup 
![img_8588_720](https://github.com/bithyve/bitcointribe/assets/107177634/1e8ef1bb-239e-4cbd-af24-84496ecad5c9)

**Comment by Deveshshankar** [comment]
![img_8671_720](https://github.com/bithyve/bitcointribe/assets/107177634/6428ea48-05c3-4a69-8af0-f13a08c04d47)
![img_8670_720](https://github.com/bithyve/bitcointribe/assets/107177634/7e48876c-81a7-4623-a8f3-bdc1fa690a3f)

**Comment by akshay8551** [comment]
![simulator_screenshot_DE5414AB-BAFA-4F9A-98A6-DCF80ADB6268](https://github.com/bithyve/bitcointribe/assets/61345820/7ca48e5a-36a5-4731-b03c-47c71f8f5ff2)

**Comment by cakesoft-swati** [comment]
- Verified this issue on tribe app v 2.2.2(591)
