### ISSUE TITLE
Different grid types for Border Wallets

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6659]
On the grid screen, there should be an option to choose grid types

Types are: 
1. Words(default)
2. Number
3. Hexadecimal(base64)
4. Blank

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e7fe32c6-047a-42b3-b3fe-fe92b4d9e11b-b2ad/screen/25d2e63c-3d84-46e9-aade-811e0c6d76b4/

**Comment by cakesoft-shashank** [comment]
@akshay8551 pass `gridType` to BorderWalletGridScreen.tsx

**Comment by cakesoft-swati** [comment]
- Verified this issue on tribe app v 2.2.2(591)
