### ISSUE TITLE
Entropy Grid Download / Import 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6661]
- [x] Entropy Grid Backup (digital file download)
- [ ] Entropy Grid Regeneration (File Import)

File import is working on ios

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e7fe32c6-047a-42b3-b3fe-fe92b4d9e11b-b2ad/screen/244becc9-a5e5-4a03-b51c-766e7a970f4e/

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.2(592)
