### ISSUE TITLE
Confirmation pop up 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6667]
**Border Wallet**
1. Wallet created successfully
2. Wallet backup confirmed successfully

**Comment by akshay8551** [comment]
Done 2.

![Simulator Screen Shot - iPhone 14 Pro - 2023-08-24 at 13 17 08](https://github.com/bithyve/bitcointribe/assets/61345820/38a05f87-07d8-4700-989e-c18aad8c50c6)

**Comment by akshay8551** [comment]
Add new wallet.

![simulator_screenshot_7DB72FD7-2831-43E6-9052-3A972C768915](https://github.com/bithyve/bitcointribe/assets/61345820/2e627b34-0e1d-4d4c-b860-019d8f2e891a)

**Comment by Deveshshankar** [comment]
Completed
