### ISSUE TITLE
Backup with Keeper:Derivation path field is blank.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6669]
![Screenshot_2023-08-17-14-54-29-14_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/528a9d0f-07c2-405a-bfb0-5fdc2bfd4d95)

**Comment by akshay8551** [comment]
Resolved,
![simulator_screenshot_38BB70A5-DC14-4F66-BFE1-0C87751E23C7](https://github.com/bithyve/bitcointribe/assets/61345820/9ae327dc-9692-4b21-8c1e-5be776be64cd)

**Comment by cakesoft-swati** [comment]
- Verified this issue on tribe app v 2.2.2(591)
