### ISSUE TITLE
Backup with Border wallet:Navigation issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6670]
https://github.com/bithyve/bitcointribe/assets/62699947/240cd542-48b6-4442-9f8d-ee174a5c1b15

- In case of backup with border wallet after checksum matching it should show successful backup message and take us back to wallet backup screen or home screen.

**Comment by Deveshshankar** [comment]
Need to check black grid option in Backup

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.2(592)
