### ISSUE TITLE
Health Check modal (Border wallet )

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6673]
Success message for health Check (Use modal we use in Backup phrase )

**Comment by akshay8551** [comment]
Added, cc-@Deveshshankar 
![simulator_screenshot_6970A51E-5141-487E-9974-4CCFCF2A129A](https://github.com/bithyve/bitcointribe/assets/61345820/328ffd86-62df-4a09-8595-f1c8d13b830f)

**Comment by Deveshshankar** [comment]
Completed
