### ISSUE TITLE
Incorrect UAI meesage 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6678]
User have not done any Backup still it says Border wallet Backup confirmed 
![IMG_8756](https://github.com/bithyve/bitcointribe/assets/107177634/fa43a519-7067-44e6-8ef7-6cf136855c47)

**Comment by Deveshshankar** [comment]
Not resolved

**Comment by akshay8551** [comment]
![simulator_screenshot_90FD1A16-8889-4EF3-9CC4-0B5D01B5E71D](https://github.com/bithyve/bitcointribe/assets/61345820/cc2f59a1-d74b-4b11-8376-96bdd8c83a59)

**Comment by akshay8551** [comment]
![simulator_screenshot_E1D45F83-4E8A-4C3B-A625-BC2D85CFB7E2](https://github.com/bithyve/bitcointribe/assets/61345820/2cc8b2e5-82d5-42a7-b216-558cf6e24ff2)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.2(592)

**Comment by cakesoft-swati** [comment]
![Screenshot_2023-08-29-11-13-48-77_20dc81889e0fe9e2ef2bddb793fc77ef](https://github.com/bithyve/bitcointribe/as
- Still it is showing incorrect UAI message.
- I had created a border wallet without passphrase and I had not done any backup still it was showing this message.

**Comment by akshay8551** [comment]
Done
![simulator_screenshot_DE34CD59-44AB-4006-A0B7-E289A5FD3F9B](https://github.com/bithyve/bitcointribe/assets/61345820/3ac3fece-494e-4e32-9748-b5a3e038d361)

**Comment by cakesoft-swati** [comment]
- Still it is showing border wallet backup confirmation but I haven't done any backup. After border wallet creation it shows this UAI message.
- Tested on Tribe App v 2.2.2(593)

**Comment by Deveshshankar** [comment]
Completed
