### ISSUE TITLE
Add Wallet 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6680]
<img width="249" alt="Screenshot 2023-08-22 at 4 11 40 PM" src="https://github.com/bithyve/bitcointribe/assets/107177634/b110e69c-e5bf-4f90-af89-a878df0632e5">

**Comment by akshay8551** [comment]
Resolved,
![simulator_screenshot_9AA7FC2C-F97C-4045-B82D-DA600632EFFA](https://github.com/bithyve/bitcointribe/assets/61345820/2a5eefff-fb0a-4d30-920b-f35c208dab10)

**Comment by Deveshshankar** [comment]
Completed
