### ISSUE TITLE
Preview Pattern:Navigation issue in account creation.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6684]
https://github.com/bithyve/bitcointribe/assets/62699947/1cc893b7-ca31-42db-bb66-39cf7b661a86

- When we click on the Done button on the preview pattern screen, it takes us to the setting screen.

**Comment by akshay8551** [comment]
Resolved,

https://github.com/bithyve/bitcointribe/assets/61345820/d7697536-e45e-4f8a-b818-04ecc00bebc7


https://github.com/bithyve/bitcointribe/assets/61345820/9ec1b9dd-ef44-4d0d-9adf-1039cc7147f9

**Comment by Deveshshankar** [comment]
still the same issue in add Border wallet flow

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.2(592)

**Comment by Deveshshankar** [comment]
Not able to check because unable to create wallet from home page
