### ISSUE TITLE
Wallet creation:UI issue on create pattern screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6685]
![IMG_8754](https://github.com/bithyve/bitcointribe/assets/62699947/b5207da9-dec5-4396-894d-5e6d9a89355f)
- Some numbers are getting cut during pattern selection.

**Comment by akshay8551** [comment]
Resolved,
![simulator_screenshot_D30E3868-1CF9-4111-BF7B-3E7910D36DB3](https://github.com/bithyve/bitcointribe/assets/61345820/3e0bc346-76ce-4ca4-90e5-1a4f189f6585)

**Comment by cakesoft-swati** [comment]
- Verified this issue on tribe app v 2.2.2(591)
