### ISSUE TITLE
Wallet Backup after recovery.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6686]
![IMG_1070](https://github.com/bithyve/bitcointribe/assets/62699947/0f05a573-bc3a-4aa3-858c-59a316d7e32d)
- After Border Wallet recovery there was no green tick on 'Backup with Border Wallet'.

**Comment by akshay8551** [comment]
![simulator_screenshot_F416F50B-F4AD-4342-8121-A1FE3527661A](https://github.com/bithyve/bitcointribe/assets/61345820/19515089-8aa5-4eb9-871d-bdfea72e50fd)

**Comment by akshay8551** [comment]
![simulator_screenshot_8AED2EE8-B476-4250-9DD6-5224B6E64D6C](https://github.com/bithyve/bitcointribe/assets/61345820/079c9bca-2421-4dcb-8121-46f23ccb2ebd)

**Comment by cakesoft-swati** [comment]
- Verified this issue on tribe app v 2.2.2(591)
