### ISSUE TITLE
Home screen: UI issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6692]
![Screenshot_2023-08-24-13-34-05-65_20dc81889e0fe9e2ef2bddb793fc77ef](https://github.com/bithyve/bitcointribe/assets/62699947/5e475827-b90f-4e3f-bd09-a491f9e3303c)
![Screenshot_2023-08-24-13-40-30-14_20dc81889e0fe9e2ef2bddb793fc77ef](https://github.com/bithyve/bitcointribe/assets/62699947/44b1d413-8637-4218-9776-7777c72cee87)
- Account tiles are cutting and due to this unable to add multiple border wallet.

**Comment by akshay8551** [comment]
Resolved,
https://github.com/bithyve/bitcointribe/assets/61345820/b16fe1c2-5317-452b-ae25-3c9fe451187b

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.2(593)
