### ISSUE TITLE
Unable to add Border Wallet for the first time in the upgraded app scenario.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6693]
https://github.com/bithyve/bitcointribe/assets/62699947/63a186fc-c3cb-488c-8a68-8279a8b510f4

**Comment by cakesoft-swati** [comment]
- Still it is happening in Tribe app v 2.2.2(591)

**Comment by pratyakxx** [comment]
1. Try it on fresh app.
2. Try upgrading from the last live version v2.2.1 to v2.2.2

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.2(593)
