### ISSUE TITLE
Download grid:UI changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6699]
![IMG_1113](https://github.com/bithyve/bitcointribe/assets/62699947/e62c6b38-73a4-47f7-b140-1a8db473e5a1)
- Remove first option : "Download with Encryption"
- Second option should be only : "Download"

**Comment by akshay8551** [comment]
Resolved,
![simulator_screenshot_D70A6EED-F0FC-4C1F-A477-FFFCF6135AE4](https://github.com/bithyve/bitcointribe/assets/61345820/a2b124d5-ef5b-4783-af47-b546956a93fd)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.2(592)
