### ISSUE TITLE
Version History 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6700]
User has created a new wallet but in version history it says restored wallet 
![img_8798_720](https://github.com/bithyve/bitcointribe/assets/107177634/dd728a53-8b37-44cb-b591-80440c974f64)

**Comment by akshay8551** [comment]
Done.
![simulator_screenshot_EA2B4B16-7954-402E-B844-1E19F7339329](https://github.com/bithyve/bitcointribe/assets/61345820/9cb1be32-c0ec-4db9-b619-a3ec73c8e519)

**Comment by Deveshshankar** [comment]
resolved
