### ISSUE TITLE
PDF import error in some Android

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6706]
This bug affects only some Android...

https://github.com/bithyve/bitcointribe/assets/62699947/1449c672-bdc8-456a-aed1-a9ce9babff61

- Getting error after uploading the PDF.

**Comment by akshay8551** [comment]
As we discussed, Whenever PDF reading failed in some Android/IOS devices we showed an error modal for that.

**Comment by Deveshshankar** [comment]
ok closing
