### ISSUE TITLE
Text update 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6709]
![img_9001_720](https://github.com/bithyve/bitcointribe/assets/107177634/659333dc-9262-49bf-9b92-41501369c9d1)
![img_9002_720](https://github.com/bithyve/bitcointribe/assets/107177634/c3d5e3cf-f966-4cc6-ae26-6083fca0d931)
![screenshot_2023-08-29_at_12 59 14_pm_720](https://github.com/bithyve/bitcointribe/assets/107177634/77c93713-903d-4cf0-8494-e4f4119bb40b)

**Comment by akshay8551** [comment]
Done.

![simulator_screenshot_A3C7E1DE-9358-4FDB-8D84-8FA76C3A8A9D](https://github.com/bithyve/bitcointribe/assets/61345820/77bb9218-5b29-4581-af61-f9a0d841021c)

![simulator_screenshot_145D34D1-EC25-4563-934F-D418B93EC088](https://github.com/bithyve/bitcointribe/assets/61345820/3bad78ec-71aa-4cf2-b046-4236a66f63b0)
