### ISSUE TITLE
Add Test Account (not default) 

### ISSUE THREAD

**Issue by antuz123** [bithyve/bitcointribe#6715]
- [x] Test Account to be hidden by default when a new wallet is created. 

- [x] The user can add a Test Account like Border Wallet or LN. Once added, the account is unhidden. 

(Currently Checking Account is showing at the bottom and Test on the top. Does not look right)

**Comment by summikhan11** [comment]
Home:
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/1d82e7da-4b46-45da-8a65-46adea2097a9/

Add Account/ Wallet
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/6d2d2939-b83f-4fbe-9f2f-3a652ef3fb63/

**Comment by akshay8551** [comment]
Done.
![simulator_screenshot_2899FF38-E893-41F5-8E22-E84B48A9C5E7](https://github.com/bithyve/bitcointribe/assets/61345820/98ea3f38-04cf-4a00-9a28-9059df06fa67)

![simulator_screenshot_74DF0850-45BA-4239-B77B-4E40CD02D814](https://github.com/bithyve/bitcointribe/assets/61345820/9ae37b5c-2ae6-4350-b2e0-2b38053bf2ce)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(616)
