### ISSUE TITLE
Backup with Border wallet option should be only visible for Border wallet account

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6717]
![Screenshot_2023-08-30-14-11-20-68_20dc81889e0fe9e2ef2bddb793fc77ef](https://github.com/bithyve/bitcointribe/assets/62699947/d48b1a15-7659-46d1-bc36-550c5fa67802)

Backup option should be visible on Border account/wallet.

- Need to change subtext.

**Comment by Deveshshankar** [comment]
Completed
