### ISSUE TITLE
Hidden account funds should not be visible 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6723]
The hidden accounts fund should not be shown in total amount at Home page if a user hides a account, balance should also be hidden

**Comment by Deveshshankar** [comment]
refresh is not working

**Comment by akshay8551** [comment]
Resolved,

![Simulator Screen Shot - iPhone 14 Pro - 2023-12-27 at 09 49 59](https://github.com/bithyve/bitcointribe/assets/61345820/cbdfe3dc-f692-4dff-bd49-5ea230088d62)

![Simulator Screen Shot - iPhone 14 Pro - 2023-12-27 at 09 50 12](https://github.com/bithyve/bitcointribe/assets/61345820/b50397cf-f910-4745-9de9-0537284edf07)

**Comment by Deveshshankar** [comment]
Completed
