### ISSUE TITLE
Backup:Entropy grid did not show the words.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6732]
- The entropy grid did not show the words during one of the back-up/restore steps,instead it was blank.
- User had to enter their pattern over the blank grid before words are shown. 
- User - MT**
- Device specification: iphone 11 Pro Max,

**Comment by akshay8551** [comment]
Not Reproducible. CC- @Deveshshankar , @cakesoft-swati

**Comment by Deveshshankar** [comment]
Not reproducible
