### ISSUE TITLE
Border wallet: Know more showing a description for Checking Acount.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6733]
- Border wallet's know more section is showing a description for Checking account.
![IMG_1144](https://github.com/bithyve/bitcointribe/assets/62699947/32f3f417-9e7b-45f7-bd50-f570813d6ee3)

**Comment by akshay8551** [comment]
Hide the Know more button for now.
![simulator_screenshot_13BF2E3A-673A-4DA2-A64C-FA189B7E8704](https://github.com/bithyve/bitcointribe/assets/61345820/f0c3a8bd-5db1-4586-b726-10707b87e734)

**Comment by cakesoft-swati** [comment]
- We removed the Know More from Border wallet for now.
- - Verified this issue on Tribe app v2.2.4(598)
