### ISSUE TITLE
Border Wallet:Check the logo.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6734]
![IMG_1145](https://github.com/bithyve/bitcointribe/assets/62699947/4ccc525a-b81d-407b-8644-fbbad73595fe)
- Logo here is green same as checking account under Account management.
- One of our user's original Border wallet is located in the "Checking account"section and has a green logo and a green header.A second border wallet he has created having an orange BW logo ,but the same green colour header as the checking account which could be confusing to user.

**Comment by akshay8551** [comment]
![simulator_screenshot_A67C8292-98A3-4E40-AF21-8030C804B05F](https://github.com/bithyve/bitcointribe/assets/61345820/3cbbc1a4-5fec-4cec-9b60-ae2e1bda2cd1)

![simulator_screenshot_30A6E393-11D8-4E6C-91A9-43BC274FB218](https://github.com/bithyve/bitcointribe/assets/61345820/7224bca0-6938-46b4-aded-6850995aea42)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v2.2.4(598)
