### ISSUE TITLE
Border wallet: Need an import option.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6736]
- There should be an option to add a Border wallet from an existing entropy grid.

**Comment by akshay8551** [comment]
Add this UX after Add new BW(Home screen modal)
![Simulator Screen Shot - iPhone 14 - 2023-09-04 at 12 09 48](https://github.com/bithyve/bitcointribe/assets/61345820/95b20901-96e1-451d-a47a-1417b79774e7)

**Comment by cakesoft-shashank** [comment]
Enter 12 words remaining

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.2.4(599)
