### ISSUE TITLE
Forgot passcode 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6740]
Need to Remove forget passcode flow Because we don't have this feature anymore
![img_9596_720](https://github.com/bithyve/bitcointribe/assets/107177634/be3314e8-137c-4763-b90c-9a8151a58cc5)

**Comment by cakesoft-swati** [comment]
- Still it is showing the "Forgot passcode" option.
- Tested in Tribe app v 2.3.0(616)

**Comment by Deveshshankar** [comment]
still I can see in iOS

**Comment by cakesoft-swati** [comment]
- verified this issue on Tribe app v 2.3.0(619)
