### ISSUE TITLE
Forgot pattern : error message 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6741]
When user clicks on forgot pattern the passcode entry screen comes but the error message appears even if the passcode was not entered.
![img_9608_720](https://github.com/bithyve/bitcointribe/assets/107177634/f373e317-b1ae-4d15-9e58-4333bc9a9d85)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(616)
