### ISSUE TITLE
Wallet backup alert 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6742]
Backup was done still it says to Backup .....
![img_9619_720](https://github.com/bithyve/bitcointribe/assets/107177634/40dcca1c-cbd8-46c8-a28e-681b297a562c)

**Comment by akshay8551** [comment]
At least 2(Seed, Backup BW) backup complete then alert goes away,
 
![simulator_screenshot_59E8DE69-89DF-44D2-98C6-3E90CF63C55C](https://github.com/bithyve/bitcointribe/assets/61345820/0b60d94d-b42c-4ade-8fd9-c9d843f4f789)

![simulator_screenshot_68B5A67B-5E0D-4955-A214-93A257A47CA5](https://github.com/bithyve/bitcointribe/assets/61345820/efaa8db7-b7d0-4bbe-a6d7-8d89de1820b6)

**Comment by Deveshshankar** [comment]
Completed
