### ISSUE TITLE
creating passcode (Keeper \ Tribe )

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6743]
- [ ] ** while creating passcode** Your app storage is encrypted by the passcode. You will not be able to log in if you forget the passcode and will have to recover your wallet using the recovery flow”
- [ ] **Error case passcode** On the retry screen “You have entered an incorrect passcode. Pls, try again. If you don’t remember your passcode, you will have to recover your wallet through the recovery flow”
- [ ] If one has not done the backup he can't access his wallet, we don't allow forget passcode

**Comment by Deveshshankar** [comment]
Not resolved in iOS

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(619)
