### ISSUE TITLE
Share QR:QR is not visible while sending the Gift via QR

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6744]
- "Scan the QR and receive bitcoin in your Bitcoin Tribe bitcoin wallet.
- Getting only this while sending the gift via Share QR option.
- Sending QR as an image is not visible

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(619)

**Comment by Deveshshankar** [comment]
Completed
