### ISSUE TITLE
Create a pattern: App is crashing on scrolling.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6748]
https://github.com/bithyve/bitcointribe/assets/62699947/b340d93b-3c67-4201-9d17-6df06f9a9950

https://github.com/bithyve/bitcointribe/assets/62699947/4767efea-50fb-4008-a20d-c2fa322f3c10

- As soon as the grid opens up and we scroll the page fast, the app is crashing.
- It is happening on Border account and on border wallet creation.

**Comment by Deveshshankar** [comment]
Resolved gave patch
