### ISSUE TITLE
Passphrase: UI changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6756]
- In passphrase field when we left blank,the following message appears:
"Please enter passphrase and confirm passphrase".
- On the passphrase screen ideally the Next button should not be enabled unless the passphrase is entered and matches. Else the user can only skip. 
**- Message suggestion: “Please enter Passphrase and confirm or Skip to proceed without it”.**
![IMG_1161](https://github.com/bithyve/bitcointribe/assets/62699947/a2551f4a-fb35-47da-8f64-1573a3585dc5)

**Comment by akshay8551** [comment]
Resolved.
![simulator_screenshot_195E2A24-1054-4C56-B6C7-A061809B72A4](https://github.com/bithyve/bitcointribe/assets/61345820/49a7adb8-7aea-40b1-bb9f-3f3b706ed3f4)

**Comment by Deveshshankar** [comment]
Completed
