### ISSUE TITLE
BW Tile colour 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6760]
https://xd.adobe.com/view/e7fe32c6-047a-42b3-b3fe-fe92b4d9e11b-b2ad/screen/15bb4411-76f4-4a60-99f1-c1790bc288e8/

**Comment by akshay8551** [comment]
Resolved,
![simulator_screenshot_B4B0D221-0CC4-4E8C-800E-1CA205A263B8](https://github.com/bithyve/bitcointribe/assets/61345820/fd9b45d5-dedc-467f-ae7c-b935a37ab514)

**Comment by Deveshshankar** [comment]
Completed
