### ISSUE TITLE
Android app is crashing on Upload grid .

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6762]
- Android app is crashing on upload grid when we import grid downloaded from ios.
- but same grid is working on ios.
https://github.com/bithyve/bitcointribe/assets/62699947/873ffb13-29ae-478b-98f1-99d7a35671ee

**Comment by cakesoft-shashank** [comment]
Duplicate issue. If grid detection fails then we're showing an error

**Comment by Deveshshankar** [comment]
Completed
