### ISSUE TITLE
Border wallet:Learn More.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6763]
- Need a learn more screen n text for Border wallet.

**Comment by akshay8551** [comment]
Done,
![simulator_screenshot_B8E52358-D36E-44DC-B313-D3FD57A7860F](https://github.com/bithyve/bitcointribe/assets/61345820/697c1c4c-057d-461e-9ea2-a30e14fb9d4b)


![simulator_screenshot_1B98C76C-1093-47C8-BA47-DB871E513D03](https://github.com/bithyve/bitcointribe/assets/61345820/ecc3ad31-db4b-4d2c-bc9f-51e0c3b66987)

**Comment by Deveshshankar** [comment]
Completed
