### ISSUE TITLE
Checking account refresh issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6778]
- Checking account is taking too long to refresh.And due to this I'm unable to see the transactions.

**Comment by cakesoft-neha** [comment]
Not reproducible. Refresh is working fine.

**Comment by cakesoft-swati** [comment]
- Still facing the refresh issue. I'm able to do pull down to refresh but it is not showing me the transaction.
- Tested in tribe app v 2.3.0(616)

**Comment by Deveshshankar** [comment]
Completed
