### ISSUE TITLE
Account management:App is crashing on View account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6779]
https://github.com/bithyve/bitcointribe/assets/62699947/da26917e-cd9a-45cc-a15f-749d85ae5ae5

- After successfully unhiding the account when we click on "View Account", the app is crashing.

**Comment by cakesoft-neha** [comment]
Fixed issue in 56d3ae26fdd1ee57442b37b1e22e0c255f5a4a29[](url)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(616)
