### ISSUE TITLE
Edit wallet Name:Navigation issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6782]
https://github.com/bithyve/bitcointribe/assets/62699947/7004b53c-54e9-427f-b424-4bb766eac5e1

- After successfully changing the wallet name when we click on Home,it takes us to the App Info screen instead of home screen.

**Comment by cakesoft-neha** [comment]
Fixed in 03e135391740512bb8fd0d7f5720e71b0f0193ae
