### ISSUE TITLE
Bitcoin Tribe Community Telegram Group:Navigation issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6783]
https://github.com/bithyve/bitcointribe/assets/62699947/80953fbb-4be1-4606-a5d1-c55484daa96c

- App Telegram link takes us to this website instead of Telegram group.

**Comment by cakesoft-swati** [comment]
- Still it is not taking us to the Telegram group.
- Tested this issue on Tribe app v 2.3.0(616)

**Comment by Deveshshankar** [comment]
resolved on  Version 2.3.0 (618)
