### ISSUE TITLE
Associate a contact:Not showing contact list.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6785]
https://github.com/bithyve/bitcointribe/assets/62699947/4cf8afe2-2239-4de7-80f2-f6835530ba22

- Despite granting access permission, it is not showing the contact list.

**Comment by cakesoft-vijaysingh** [comment]
fixed this issue in commit: https://github.com/bithyve/bitcointribe/commit/48988ff73e8c5f94f43e9ab3888b0bcbc1aadf38

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(616)
