### ISSUE TITLE
Remove gift TAB from F&F

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6787]
![img_0380_720](https://github.com/bithyve/bitcointribe/assets/107177634/a092fc32-815d-440a-b1d4-ac566aa73299)

**Comment by cakesoft-neha** [comment]
Fixed in 73e609f90fb906595aa28e21fc4b399764afe11c

**Comment by Deveshshankar** [comment]
@cakesoft-neha 1.Please remove gift from this screen as we have another tab for Gift
2.Shift F&F a little top in place of gift

**Comment by Deveshshankar** [comment]
To be checked in next release

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(619)
