### ISSUE TITLE
Change icon BW 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6793]
account management 
![img_0430_720](https://github.com/bithyve/bitcointribe/assets/107177634/6aaf2f1d-f0f9-4641-897e-5cf2c5fbeba7)

**Comment by akshay8551** [comment]
Done.

![simulator_screenshot_D1A42E61-ABA9-4E5C-9CC2-053716A35E3F](https://github.com/bithyve/bitcointribe/assets/61345820/ae5c45c7-b372-4d64-a13f-365e48482d59)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(616)
