### ISSUE TITLE
Border wallet:Unable to upload pdf.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6807]
![IMG_20230923_143732](https://github.com/bithyve/bitcointribe/assets/62699947/69b56b44-ccb1-4031-a9bb-5d61c5437a58)
-   getting this error while uploading pdf on sparrow.
- And on iOS device it is saying that No wallet found .I'm uploading same pdf still it is not accepting.

**Comment by Deveshshankar** [comment]
Completed
