### ISSUE TITLE
header title twice in contacts list for associate contacts

### ISSUE THREAD

**Issue by cakesoft-vijaysingh** [bithyve/bitcointribe#6844]
![Screenshot_2023-10-04-12-58-54-688_io hexawallet hexa development](https://github.com/bithyve/bitcointribe/assets/86593201/ae84d7a3-975e-4e90-87cf-1b9e57970eb4)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.3.0(619)
