### ISSUE TITLE
Test account 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6850]
- [ ] Need a loader 
- [ ] After unhiding test account is not Visible on home 

![img_6219_720](https://github.com/bithyve/bitcointribe/assets/107177634/9b14a502-0215-4aff-b47a-bf1c50edf0ec)

**Comment by cakesoft-swati** [comment]
- Still having the same issue.Tested on dev app v 2.3.0(619).

**Comment by Deveshshankar** [comment]
Completed
