### ISSUE TITLE
Backup phrase navigation

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6853]
While entering Backup phrase if on the first box word is entered successfully the pointer should go on 2nd automatically 

https://github.com/bithyve/bitcointribe/assets/107177634/d63bf7d1-9eb0-438e-93e5-f4db591b304e

**Comment by Deveshshankar** [comment]
Not resolved

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
