### ISSUE TITLE
app not responding after upgrade 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6859]
was on older version and Upgraded to 2.2.7 (603)

https://github.com/bithyve/bitcointribe/assets/107177634/715468aa-0a81-4bf3-8dde-c95e8546b4b9

**Comment by cakesoft-shashank** [comment]
Fixed in build #604

**Comment by cakesoft-swati** [comment]
- Verified this issue on keeper app v 2.2.7(604)
