### ISSUE TITLE
Transaction Priority:Transaction priorities are not visible.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6867]
![Screenshot_2023-10-10-10-20-01-11_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/6a919f7a-057a-45fd-acaa-628100049800)
- I was trying to send from Test account to checking account but transaction priorities were not visible.

**Comment by cakesoft-neha** [comment]
This issue will be resolved once the node connection issue is fixed.

**Comment by akshay8551** [comment]
Working fine. 

Uploading Screen Recording 2024-01-04 at 12.47.15 PM.mov…

**Comment by akshay8551** [comment]
Working fine. 

https://github.com/bithyve/bitcointribe/assets/61345820/b4f55b1b-939c-4471-846c-de4bd144b5fe

**Comment by Deveshshankar** [comment]
Resolved
