### ISSUE TITLE
Send screen:UI issues.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6868]
![Screenshot_2023-10-10-10-21-01-52_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/6f573dce-628b-4504-9fce-473672ed9bc4)
- This cross button is not working.Unable to cancel this send to address field.
- If cross button is working in case of more than one address then that cross button is not required for one address.

![Screenshot_2023-10-10-10-22-06-82_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/d5a17889-ec6c-41f7-b580-b8beef453e76)
- Add Recipient is not working.

**Comment by Deveshshankar** [comment]
Completed
