### ISSUE TITLE
Checking account:Unable to see the transactions in checking account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#6870]
![Screenshot_2023-10-10-10-48-21-33_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/6ab8fd1c-ea62-4d42-a6a1-47fde9bb4aa0)
- I sent some sats in checking account and refreshed that account but still it is not showing the transaction.

**Comment by Deveshshankar** [comment]
Completed
