### ISSUE TITLE
small device iOS 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6875]
For example, when pressing the back arrow on the top left of the screen, the time at the top of the
phone overlaps the back arrow, making it hard to click and see, some apps allow you to switch
back to the app when you tap next to the time on iOS so it causes the bitcoin wallet to exit
to a different app instead of going back
<img width="211" alt="Screenshot 2023-10-11 at 11 20 17 AM" src="https://github.com/bithyve/bitcointribe/assets/107177634/cc77b9ce-aa1c-4c00-ae90-4ce184bf4c75">

**Comment by akshay8551** [comment]
Done,
![simulator_screenshot_079F1CCA-C57F-4F72-86D2-6607FE71EC1A](https://github.com/bithyve/bitcointribe/assets/61345820/502bf101-29ea-4c96-bf8b-cf177c77362d)

**Comment by Deveshshankar** [comment]
iOS not out yet
