### ISSUE TITLE
iOS notch covers the"account settings"

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6876]
- [x] The iphone 14/15 notch covers the"account settings" text

- [x] Also when I press the "X" button on this screen to go back to home screen it doesn't work as it

overlaps with the time on the iPhone
![Image from iOS (4)](https://github.com/bithyve/bitcointribe/assets/107177634/c68051da-d9d6-470a-b022-9fedbe21f753)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/b0f0fb57-216c-45cb-a959-8da490fc61e6/

**Comment by akshay8551** [comment]
Resolved,

![simulator_screenshot_595D1EC8-6FED-4FC4-8445-432104345F0C](https://github.com/bithyve/bitcointribe/assets/61345820/729cb78c-9775-4782-9325-bbfdb16cb1b5)

**Comment by Deveshshankar** [comment]
Ios is not out yet

**Comment by akshay8551** [comment]
Resolved,

![simulator_screenshot_6D8BCF68-39E5-4A86-990B-6700D2574149](https://github.com/bithyve/bitcointribe/assets/61345820/da9c776f-f725-4836-b355-8a10d66f5f0c)

**Comment by Deveshshankar** [comment]
Completed
