### ISSUE TITLE
on small device words not displayed all at a time

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6877]
![img_6227_720](https://github.com/bithyve/bitcointribe/assets/107177634/7578e5a5-07fd-45de-81b5-36bc96deb1e6)
freezes/general reliability. When generating the seed for the border wallet not all 12 words display on the screen at once for smaller screen phones.

**Comment by akshay8551** [comment]
iPhone SE

https://github.com/bithyve/bitcointribe/assets/61345820/588f200a-71ce-4f17-bdeb-ca85d595ce96

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e7fe32c6-047a-42b3-b3fe-fe92b4d9e11b-b2ad/screen/91a10138-860d-4a70-a05f-ae98d1d60d8f/

**Comment by Deveshshankar** [comment]
resolved
