### ISSUE TITLE
entropy grid doesn't show in Preview

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6894]
if you choose a pattern at the very bottom of the entropy grid, it doesn't show in the Preview
![img_1383_720](https://github.com/bithyve/bitcointribe/assets/107177634/c5fe9fd0-885a-4f6a-8e6c-516d69d1d514)
- We need to have to scale down and keep it in the same proportion to view in preview.

**Comment by akshay8551** [comment]
Resolved,

![simulator_screenshot_E27C596E-7307-4BD1-B762-C8FBF25D0984](https://github.com/bithyve/bitcointribe/assets/61345820/1d320537-9190-4d30-9057-ba29e9a1885b)

![simulator_screenshot_F953C666-7D78-4307-A639-213E54C65389](https://github.com/bithyve/bitcointribe/assets/61345820/b8c60b7b-b21a-4623-8f7e-47d9ac1ed767)

**Comment by cakesoft-swati** [comment]
- Verified this on Tribe app v 2.2.7(606)
