### ISSUE TITLE
small ui bugs 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6900]
![img_1744_720](https://github.com/bithyve/bitcointribe/assets/107177634/9b6232c0-0d44-4431-a6ee-26856677b578)
![img_1743_720](https://github.com/bithyve/bitcointribe/assets/107177634/43821509-c621-4426-969d-2b11c12233a2)
![img_1742_720](https://github.com/bithyve/bitcointribe/assets/107177634/afcbb375-3826-44c0-8e81-7a957cfdcda0)
![img_1742_720](https://github.com/bithyve/bitcointribe/assets/107177634/506c97a6-b592-4482-8b0b-781089818a7f)
![img_1741_720](https://github.com/bithyve/bitcointribe/assets/107177634/0e85762e-e028-443b-aae3-539ba8ec2f31)
![img_1740_720](https://github.com/bithyve/bitcointribe/assets/107177634/75b28605-b10e-4d82-a6e9-0b99c457eb0b)

**Comment by akshay8551** [comment]
![simulator_screenshot_D0029450-DEC8-4E07-8D45-B06CDBD07E69](https://github.com/bithyve/bitcointribe/assets/61345820/e63e7175-0473-4457-aa51-7b4c73b11691)

**Comment by akshay8551** [comment]
![simulator_screenshot_BDA3A9CC-05C5-4991-AE23-B0024E6EBBF5](https://github.com/bithyve/bitcointribe/assets/61345820/84e63588-3af1-4ff8-9f16-ea7ff476ccf4)

**Comment by Deveshshankar** [comment]
Resolved
