### ISSUE TITLE
Pattern not visible 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6910]
The pattern does not show up on the screen where we view words and the grid.
For eg :I have selected three words at the top of the grid and the rest at the bottom, but they do not appear on the screen.
![screenshot_20231129_134043_bitcoin_tribe_dev_720](https://github.com/bithyve/bitcointribe/assets/107177634/0da25996-e1c4-4913-aab8-8efe4a1e0137)

**Comment by akshay8551** [comment]
![simulator_screenshot_FA2C9A86-E3E9-4A15-B327-3A111A79399C](https://github.com/bithyve/bitcointribe/assets/61345820/5cca67e9-0f9c-40fe-87f8-f9d7b1294e2b)

![simulator_screenshot_01B3D2AD-80B7-4779-ABAE-79FA5EA29C1A](https://github.com/bithyve/bitcointribe/assets/61345820/0fbf196a-3ac4-446f-9662-303d0b9fd16d)

**Comment by Deveshshankar** [comment]
Completed
