### ISSUE TITLE
Incorrect passcode alert message 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6911]
When a user forgets the pattern-to-view pattern user attempts to enter a passcode, an alert is triggered even before entering the passcode.
![img_1754_720](https://github.com/bithyve/bitcointribe/assets/107177634/94ca8cea-87fc-4228-b968-553e9009454c)

**Comment by Deveshshankar** [comment]
Error message is gone but preview is not visible it is redirecting to Home instead @akshay8551

**Comment by Deveshshankar** [comment]
https://github.com/bithyve/bitcointribe/assets/107177634/129602b0-4223-40bd-ae28-1c60f010f65e

**Comment by akshay8551** [comment]
https://github.com/bithyve/bitcointribe/assets/61345820/345891a8-353c-4ed1-b478-150622ca5b63

**Comment by Deveshshankar** [comment]
Fixed
