### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6922]
- [x] Alignment ![IMG_2325](https://github.com/bithyve/bitcointribe/assets/107177634/de22bee5-99cf-4d14-83c4-3a6f88101538)

![img_2299_720](https://github.com/bithyve/bitcointribe/assets/107177634/f8b0eec9-d764-4a92-827c-5d7492dad2d2)

- [x] CTA does not work 
![img_2316_720](https://github.com/bithyve/bitcointribe/assets/107177634/09d88f45-409d-44bb-9088-914d12d55aef)

- [x] Remove shadow

![IMG_2328](https://github.com/bithyve/bitcointribe/assets/107177634/5e0a08c3-25a0-4aec-a7db-8ca11ec4db46)

**Comment by akshay8551** [comment]
Resolved,

![simulator_screenshot_C5FCFA5F-4F7F-411B-AFA5-605FA4497853](https://github.com/bithyve/bitcointribe/assets/61345820/32f603b4-01aa-4538-ae5d-7322fb0375af)

![simulator_screenshot_B90BF14E-ACEE-4E6F-8BCD-CB896EE89712](https://github.com/bithyve/bitcointribe/assets/61345820/d58f47d4-9e47-4e4a-badd-fd3393c96ce7)

**Comment by akshay8551** [comment]
![simulator_screenshot_CDD2FA3F-DA4A-4BAD-B504-26CC6E85743B](https://github.com/bithyve/bitcointribe/assets/61345820/a13f6d0a-a534-482f-9802-35534d326921)

**Comment by Deveshshankar** [comment]
Resolved
