### ISSUE TITLE
Toast message is not as per design 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6923]
![IMG_2341](https://github.com/bithyve/bitcointribe/assets/107177634/b70d2689-fcb0-465a-a410-8f96ec0a09ba)
![IMG_2342](https://github.com/bithyve/bitcointribe/assets/107177634/427e78ac-1a74-41ec-ba93-db7f622bb508)

**Comment by akshay8551** [comment]
Done.
![Screenshot_20240103-134501_Bitcoin Tribe dev](https://github.com/bithyve/bitcointribe/assets/61345820/7bc5e09f-a9c2-48db-be2a-3209930bf4c9)

**Comment by Deveshshankar** [comment]
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/c1e1e673-c902-4e16-b11c-ec8d609ac716/ make as per design across the app @akshay8551

**Comment by akshay8551** [comment]
<img width="328" alt="Screenshot 2024-01-10 at 4 25 03 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/119033d0-d050-4e1c-a42f-d01408e81bfa">

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(626)
