### ISSUE TITLE
App crash on issue Coin / collectibles 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6925]
app is crashing when ever user is trying to issue asset without adding anything (basically in null case)
Crash on pressing the CTA "Issue asset"
Version 2.3.0 (619) dev app 
![IMG_2352](https://github.com/bithyve/bitcointribe/assets/107177634/fd80ca5c-5329-4fa1-a806-6dcef6feb69a)
![IMG_2353](https://github.com/bithyve/bitcointribe/assets/107177634/c2ff3477-0a5f-4587-a743-46644b7a058b)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(626)
