### ISSUE TITLE
Collectibles: Getting error while issuing asset 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6927]
![img_2354_720](https://github.com/bithyve/bitcointribe/assets/107177634/efaeb0c6-38b6-4166-b788-03625b0837c7)

**Comment by cakesoft-shyam** [comment]
FYI- @Deveshshankar 
This issue will be fixed once rbg pacakge is done.

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
