### ISSUE TITLE
Heading and subheading For Coin / Collectibles 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6928]
- [x] Heading :  Issue Collectibles and Issue Coin (earlier it was small c )

![img_2345_720](https://github.com/bithyve/bitcointribe/assets/107177634/87e2aecb-7646-4b24-93b1-4becee7e8135)
![img_2346_720](https://github.com/bithyve/bitcointribe/assets/107177634/cd727d09-6745-4bb9-8c83-55f2d579bc1b)

**Comment by akshay8551** [comment]
Done.

<img width="332" alt="Screenshot 2024-01-03 at 11 27 32 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/f253b7a7-f682-4cce-8318-10694e79f871">

<img width="332" alt="Screenshot 2024-01-03 at 11 27 43 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/f5ec1b90-bcb9-47a0-b8d2-c5dc7bd2232a">

**Comment by Deveshshankar** [comment]
coin and collectibles are in small make it caps C

**Comment by Deveshshankar** [comment]
Rgb issue not able to test

**Comment by cakesoft-swati** [comment]
- coin and collectibles are in small make it caps C

**Comment by cakesoft-swati** [comment]
https://github.com/bithyve/bitcointribe/issues/6569#issue-1781131879
