### ISSUE TITLE
Modify Header according to new UX across the app

### ISSUE THREAD

**Issue by akshay8551** [bithyve/bitcointribe#6929]
Ref Link: 

https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/352dbf6b-a7e2-49a0-a1a6-d85595415db3/specs/

**Comment by akshay8551** [comment]
Done,

![simulator_screenshot_AAA7B4FB-EAB4-47D5-B728-8C8981C67345](https://github.com/bithyve/bitcointribe/assets/61345820/1a22ec65-d579-4412-a14a-19a5b1991278)

![simulator_screenshot_58B701DD-EAFC-4F45-9E4C-E1643447F9FA](https://github.com/bithyve/bitcointribe/assets/61345820/7454c921-d351-410e-beab-bfb5cb21a313)

![simulator_screenshot_EE2460C7-F849-401D-B697-D151AACC2134](https://github.com/bithyve/bitcointribe/assets/61345820/cfac8014-5966-4f0d-b85e-b5f6f7f35520)

![simulator_screenshot_E29C23DF-149C-47D0-8185-28C18412FB33](https://github.com/bithyve/bitcointribe/assets/61345820/8a1993d3-df7b-4dcf-9c64-e98db5e015e7)

**Comment by akshay8551** [comment]
![simulator_screenshot_73701064-D2AE-4884-9BC7-E2ABD8B66A8D](https://github.com/bithyve/bitcointribe/assets/61345820/b23f64ec-f0b9-4a53-9154-152f7cecf50d)

![simulator_screenshot_E186C038-8187-42C3-98C6-F347621FC27D](https://github.com/bithyve/bitcointribe/assets/61345820/e2323f3a-9d08-4c7c-94ba-95d52ea5ebcb)

**Comment by Deveshshankar** [comment]
Completed
