### ISSUE TITLE
CTA "Add recipients" does not respond 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6931]
![screenshot_20231226_125947_bitcoin_tribe_dev_720](https://github.com/bithyve/bitcointribe/assets/107177634/de102392-01bc-4e2c-b00e-e04b1a5da516)

**Comment by akshay8551** [comment]
Done.

Uploading Screen Recording 2023-12-27 at 12.45.37 PM.mov…

**Comment by Deveshshankar** [comment]
Resolved
