### ISSUE TITLE
Backup phrase 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6932]
- [x] Text changes "Enter the word exactly like it was displayed"
- [x] Please change from all 3 places (2 on Backup phrase confirmation screen and Health check screen )
![screenshot_20231226_124806_bitcoin_tribe_dev_720](https://github.com/bithyve/bitcointribe/assets/107177634/8ffe34e1-c7d0-4e7c-a061-052031fc6232)

- [x] Typo error ![screenshot_20231226_124510_bitcoin_tribe_dev_720](https://github.com/bithyve/bitcointribe/assets/107177634/2c9b0925-b3b6-45eb-beb8-092e2fa0eea7)

**Comment by akshay8551** [comment]
![simulator_screenshot_F52A7D82-340D-489C-8925-4FD9F12E6018](https://github.com/bithyve/bitcointribe/assets/61345820/dce8f83b-645a-4e7b-8c82-afd25fc0edcf)

![simulator_screenshot_324360F7-F97D-47F6-936B-725A3D5A6AB9](https://github.com/bithyve/bitcointribe/assets/61345820/da85dc7c-bbd6-4148-95df-8eca4a44c366)

**Comment by Deveshshankar** [comment]
Completed 2.2.10 (615)
