### ISSUE TITLE
CTA is weird when pressed

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6933]
RealmeX7 
![screenshot_20231226_123856_gallery_720](https://github.com/bithyve/bitcointribe/assets/107177634/7bbdfc78-dfba-4298-8ddb-e580aae108f9)
![screenshot_2024-01-10-17-21-37-93_20dc81889e0fe9e2ef2bddb793fc77ef_720](https://github.com/bithyve/bitcointribe/assets/107177634/c5b9ea26-e7c1-4645-94a5-5a04294c2916)

**Comment by akshay8551** [comment]
Looks good on my side, Not able to reproduce it at my side.

https://github.com/bithyve/bitcointribe/assets/61345820/ca48051a-ba84-4feb-b2f2-05af119cf14a

**Comment by Deveshshankar** [comment]
Still getting same error in android

**Comment by Deveshshankar** [comment]
Completed
