### ISSUE TITLE
app crash on hide Test account

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6934]
- [x] App Crash on hide test account 

- [ ] Asset is not correct 

https://github.com/bithyve/bitcointribe/assets/107177634/0584d2d9-c24d-4a4e-a15c-cf5228e8317b

**Comment by akshay8551** [comment]
https://github.com/bithyve/bitcointribe/assets/61345820/aad6bd20-a8f8-4d6e-b759-004e6dab937a


https://github.com/bithyve/bitcointribe/assets/61345820/ea9e9fde-15d6-44cc-a95f-c16b13f9e321

**Comment by Deveshshankar** [comment]
Resolved in 2.2.10 (614)
