### ISSUE TITLE
F&F needs few changes 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6935]
Dev app ![screenshot_20231226_135501_bitcoin_tribe_dev_720](https://github.com/bithyve/bitcointribe/assets/107177634/5201402b-efe9-455d-8240-463f1f7c0738)

Design 
![Uploading IMG_2562.PNG…]()

https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/5259accb-bde4-45d2-a192-454209f39c9b/

**Comment by akshay8551** [comment]
Done,

![simulator_screenshot_620BF939-3572-447A-8393-B4970A8E5C8C](https://github.com/bithyve/bitcointribe/assets/61345820/0e61d8ef-e320-45fb-9100-dd264d4f2e44)

![simulator_screenshot_1C8FC8A9-4277-4C3E-8DEC-BB9B0063D96F](https://github.com/bithyve/bitcointribe/assets/61345820/b3d28cdc-2bf1-4e5c-856f-6da4ac62cb5e)

**Comment by Deveshshankar** [comment]
Completed
