### ISSUE TITLE
Add CTA to modal in BW 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6942]
Proceed 
![screenshot_20231226_161720_bitcoin_tribe_dev_720](https://github.com/bithyve/bitcointribe/assets/107177634/88ea0f9c-7ffd-437a-920e-60ce7116888b)

**Comment by akshay8551** [comment]
Done,
Changed the `Next` Button title/text 
CC - @Deveshshankar 

![simulator_screenshot_85A2BAE9-85A8-4419-8365-97EC88CE92BC](https://github.com/bithyve/bitcointribe/assets/61345820/df1e4741-a514-4c37-8093-d9491f441952)

**Comment by Deveshshankar** [comment]
We decided to change on all modals can see only on one cc @akshay8551 @cakesoft-shashank

**Comment by Deveshshankar** [comment]
Completed
