### ISSUE TITLE
Text change after backup is done 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6943]
- [x] Border Wallet backed-up successfully" Should be updated on all possible places  

![img_2563_720](https://github.com/bithyve/bitcointribe/assets/107177634/247122c7-f4ac-451a-ba9d-89d0934f3a94)

- [x] Top UAI will change according to Backup done (Backup phrase / Backup with Keeper / Border wallet Backup )

![img_2564_720](https://github.com/bithyve/bitcointribe/assets/107177634/6027fec9-a4ed-4e59-bfb3-8526c0c72629)

- [x] Checksum matched :  Border Wallet backed-up successfully" Should be done at all the places 
![img_2562_720](https://github.com/bithyve/bitcointribe/assets/107177634/82de4f18-0fb1-4bff-96bc-daaf534f8847)

**Comment by akshay8551** [comment]
Done.

![Simulator Screen Shot - iPhone 6 - 2023-12-27 at 14 22 44](https://github.com/bithyve/bitcointribe/assets/61345820/0cbcc3b5-5129-44ce-ad86-3a366590d5c8)
![Simulator Screen Shot - iPhone 6 - 2023-12-27 at 14 22 47](https://github.com/bithyve/bitcointribe/assets/61345820/236a6689-da5c-49eb-b15b-b0827acf3861)
![Simulator Screen Shot - iPhone 6 - 2023-12-27 at 14 24 53](https://github.com/bithyve/bitcointribe/assets/61345820/f8bc2b1c-b0e5-470b-a2ac-64efa7fb9c3e)
![Simulator Screen Shot - iPhone 6 - 2023-12-27 at 14 38 20](https://github.com/bithyve/bitcointribe/assets/61345820/9adbb4cc-b94a-4fb9-a7a0-185f9a3a5f6b)
![Simulator Screen Shot - iPhone 6 - 2023-12-27 at 14 38 22](https://github.com/bithyve/bitcointribe/assets/61345820/3b33422a-e802-4aca-900b-3b19e341ba3c)

**Comment by akshay8551** [comment]
Done 3. 

![Simulator Screen Shot - iPhone 6 - 2023-12-27 at 14 42 00](https://github.com/bithyve/bitcointribe/assets/61345820/4017e72b-194d-4bf4-94cd-6faf75fe62d5)

**Comment by Deveshshankar** [comment]
Completed
