### ISSUE TITLE
Check Node setting alignment 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6948]
![screenshot_2023-12-28-14-49-19-72_6ccb4bf936ab2cedd5e025652c6047ae_720](https://github.com/bithyve/bitcointribe/assets/107177634/6dbf16ee-c953-4b82-80d0-34093e29c4fc)

**Comment by akshay8551** [comment]
![Simulator Screen Shot - iPhone 14 Pro - 2024-01-02 at 08 31 03](https://github.com/bithyve/bitcointribe/assets/61345820/b0aae34d-10cb-41d1-805c-d632d4cb6097)

**Comment by Deveshshankar** [comment]
Resolved 2.3.0 (619)
