### ISSUE TITLE
Change the colour of icons according to latest Design

### ISSUE THREAD

**Issue by akshay8551** [bithyve/bitcointribe#6950]
Need assets -
 
![img_2310_720](https://github.com/bithyve/bitcointribe/assets/107177634/c3b78a92-91fb-4ac2-8d9e-7d35cccbc5c1)

**Comment by akshay8551** [comment]
@summikhan11 and @Deveshshankar Could you please share assets?

**Comment by akshay8551** [comment]
Resolved,

<img width="328" alt="Screenshot 2024-01-10 at 4 06 47 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/3e904f21-03cf-464e-95a0-c3d24f0e7e1b">

**Comment by Deveshshankar** [comment]
Completed
