### ISSUE TITLE
 Toast message 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6953]
<img width="206" alt="Screenshot 2024-01-04 at 1 06 11 PM" src="https://github.com/bithyve/bitcointribe/assets/107177634/1004e497-2191-49b3-abb3-607ab11cd688">
<img width="193" alt="Screenshot 2024-01-04 at 1 06 17 PM" src="https://github.com/bithyve/bitcointribe/assets/107177634/39f1b965-5a37-4fca-be46-9998d17441f5">

Dev app 

![img_2719_720](https://github.com/bithyve/bitcointribe/assets/107177634/e21c45b7-3c9f-4152-9907-8754c2322f0e)

![img_2720_720](https://github.com/bithyve/bitcointribe/assets/107177634/2d3d2434-d831-4db0-8660-3e4e7b7d6d1a)

**Comment by Deveshshankar** [comment]
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/grid

**Comment by akshay8551** [comment]
> https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/grid

@Deveshshankar Could you please provide content for the subtitle?

**Comment by akshay8551** [comment]
Resolved,

<img width="328" alt="Screenshot 2024-01-05 at 3 01 05 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/6cdff312-e63f-4c13-8f41-ac978afce282">
<img width="328" alt="Screenshot 2024-01-05 at 3 01 12 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/435b5a43-785b-4bb5-ba15-dfecee388487">

**Comment by akshay8551** [comment]
@Deveshshankar Would you please share subtitle's (Add amount) content?

**Comment by Deveshshankar** [comment]
not as per design

**Comment by Deveshshankar** [comment]
![screenshot_20240110_142439_bitcoin_tribe_dev_720](https://github.com/bithyve/bitcointribe/assets/107177634/1f449632-f732-4523-b017-c31096d60366)
not as per design

**Comment by akshay8551** [comment]
Resolved,

<img width="332" alt="Screenshot 2024-01-10 at 6 18 19 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/efb77df5-b229-4400-959d-20084403001c">
