### ISSUE TITLE
Assets Required.

### ISSUE THREAD

**Issue by cakesoft-shyam** [bithyve/bitcointribe#6955]
@Deveshshankar 

<img width="307" alt="Screenshot 2024-01-08 at 12 26 30 PM" src="https://github.com/bithyve/bitcointribe/assets/62867694/01f62b13-0029-45d1-bd6f-31011ac2df07">
<img width="305" alt="Screenshot 2024-01-08 at 12 28 23 PM" src="https://github.com/bithyve/bitcointribe/assets/62867694/9faf5e59-a27e-44a2-82e8-5c989957f4b5">

**Comment by Deveshshankar** [comment]
![gift 2](https://github.com/bithyve/bitcointribe/assets/107177634/068fe164-62e5-46ff-8275-6286eb488995)
![add brown](https://github.com/bithyve/bitcointribe/assets/107177634/5c2383c8-7aac-450b-bfdf-606257bf343a)
