### ISSUE TITLE
Home page need to be redesigned as per UX

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6964]
<img width="225" alt="Screenshot 2024-01-10 at 4 46 18 PM" src="https://github.com/bithyve/bitcointribe/assets/107177634/657485d5-152c-4241-98d0-d194302b4715">

![screenshot_20240110_164724_bitcoin_tribe_dev_720](https://github.com/bithyve/bitcointribe/assets/107177634/8206e60a-556e-4131-821b-c2e2da462e0d)

**Comment by akshay8551** [comment]
Resolved,

<img width="330" alt="Screenshot 2024-01-15 at 3 07 17 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/efb90e4f-8f44-4826-8525-b83082690dd4">

<img width="330" alt="Screenshot 2024-01-15 at 3 07 23 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/e88e0a5a-05a7-428e-8146-82f93b7d23be">

**Comment by Deveshshankar** [comment]
Completed
