### ISSUE TITLE
Test net sats does not appear's in Test account 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6970]
The app is connected to node still test sats does not appears in test account 
https://github.com/bithyve/bitcointribe/assets/107177634/8d4b4d7f-9b28-450c-a3f9-37eb56ca1d2d

**Comment by cakesoft-shyam** [comment]
Not able to reproduce the issue.

**Comment by Deveshshankar** [comment]
Resolved in Version 2.3.0(620)
