### ISSUE TITLE
Buy Bitcoin 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6972]
Buy Bitcoin  flow is weird android Samsung F23
https://github.com/bithyve/bitcointribe/assets/107177634/cd4942f0-cf70-4f41-8b7d-4477cebbfa53

**Comment by cakesoft-shyam** [comment]
@Deveshshankar Please check the test APK and let me know which worked for you. This is a device specific issue.

**Comment by Deveshshankar** [comment]
Still same issue Samsung F23

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
