### ISSUE TITLE
app crash after saving Pdf (android )

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6973]
App crashes when reopening after PDF save.

https://github.com/bithyve/bitcointribe/assets/107177634/57a46b5a-57c2-4228-a6c4-522127cea4b3

**Comment by akshay8551** [comment]
Working fine...

https://github.com/bithyve/bitcointribe/assets/61345820/4d0c90c7-1098-4071-9ae6-afc414715ab9

**Comment by Deveshshankar** [comment]
Resolved in Version 2.3.0(620)
