### ISSUE TITLE
Accepting Gift Performance  

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6974]
- [x] Link does not opens when clicked twice 
- [x] CTA is pressed but no animation or user messaging and gift is not able to reflect 
 
- [x] Modal comes a little slow 

![whatsapp_image_2024-01-11_at_7 15 58_pm_720](https://github.com/bithyve/bitcointribe/assets/107177634/d6d9c64b-2c3a-4a87-b96e-786865a0119f)

https://github.com/bithyve/bitcointribe/assets/107177634/8f482139-19de-4b46-a789-b11b9e93fb17

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
