### ISSUE TITLE
The flow is weird 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6982]
https://github.com/bithyve/bitcointribe/assets/107177634/41296b77-93cb-46d3-a7fa-ced0a020d89c

**Comment by akshay8551** [comment]
Working Fine..

https://github.com/bithyve/bitcointribe/assets/61345820/b60d437c-ed4c-43ec-80eb-9feb28c16213

**Comment by Deveshshankar** [comment]
Completed on 2.4.1 (631)
