### ISSUE TITLE
To implement Receive Asset & Set Default Fee Rate

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6988]
- [x] **Receive Asset (Free Faucet)**: Implement functionality for users to receive assets from a free faucet, ensuring seamless transfer and balance updates.

- [ ] **Set Default (Fee Rate):** Establish a default transaction fee rate, automatically applied unless altered by the user, balancing cost and speed.

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
- Already have an issue in sprint 29 for second option (Default Fee rate)
