### ISSUE TITLE
Upload image is misaligned 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#7004]
![Screenshot_2024-01-24-13-28-03-16_6ccb4bf936ab2cedd5e025652c6047ae.jpg](https://github.com/bithyve/bitcointribe/assets/107177634/1465ff96-33cb-4b57-ae9b-6b83293f7b5e)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
