### ISSUE TITLE
Require UI modification 

### ISSUE THREAD

**Issue by akshay8551** [bithyve/bitcointribe#7005]
<img width="333" alt="Screenshot 2024-01-24 at 2 51 03 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/4bbf107e-53f6-43a8-9545-8d2caea733ce">

**Comment by Deveshshankar** [comment]
https://xd.adobe.com/view/2af996b7-0e6e-453b-9c82-c735e28a43e7-7faa/screen/c8742d67-0105-43a7-be68-c9790da57e2a/specs/

**Comment by akshay8551** [comment]
Resolved,

<img width="322" alt="Screenshot 2024-02-21 at 9 36 13 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/f6f94e8c-4f69-47c9-9304-428393bbea4a">

<img width="322" alt="Screenshot 2024-02-21 at 9 18 11 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/01671c60-3d76-4beb-9535-f7a88881f347">

**Comment by Deveshshankar** [comment]
Completed
