### ISSUE TITLE
My Assets screen: UI issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#7015]
![Screenshot_2024-01-29-11-34-47-91_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/916a5a75-1193-41b0-9916-acad15a33359)
- Text is cutting on My Assets screen.

**Comment by akshay8551** [comment]
<img width="334" alt="Screenshot 2024-01-29 at 5 51 39 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/4c5c9057-c0a7-4b4a-9dd8-27141307b1bc">

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
