### ISSUE TITLE
Unable to download the asset image. 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#7016]
![Screenshot_2024-01-29-11-47-56-29_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/4bc028e2-a9db-4ab8-91bb-4928336c4ca7)
- Getting this "Failed to download the file" message while downloading the

**Comment by cakesoft-shyam** [comment]
FYI @cakesoft-swati 
Download now works for android, have not tested for ios yet due to ongoing rgb development. Will test it on ios once rgb is stable on ios.

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
