### ISSUE TITLE
Sync modal alignment and animation is not proper.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#7017]
https://github.com/bithyve/bitcointribe/assets/62699947/2f07cc69-635e-41ae-ad4e-c5b6d1236a68

- Sync modal is not looking proper.
- check the alignment, font.
- Animation is also not proper.

**Comment by akshay8551** [comment]
<img width="334" alt="Screenshot 2024-01-29 at 2 55 11 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/a49a6197-50a3-4187-8c73-72df4d68bec3">

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
