### ISSUE TITLE
iOS app crashing after wallet creation.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#7023]
https://github.com/bithyve/bitcointribe/assets/62699947/908b7d6c-88f3-41aa-b79a-dadb6fde46e4

**Comment by cakesoft-shyam** [comment]
@cakesoft-shashank 
This issue is fixed in this commit [ios loader fix](https://github.com/bithyve/bitcointribe/commit/2dc4bd4a83bd96deb7b831f5323c168b3a83bbe8#diff-e6f68cf46b042a3af7ac8667cddb8f733028739021fd620bd1344d0bb9abb61f)

FYI @cakesoft-swati

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
