### ISSUE TITLE
Misaligned UI on ios

### ISSUE THREAD

**Issue by cakesoft-shyam** [bithyve/bitcointribe#7025]

**Comment by cakesoft-shyam** [comment]
![WhatsApp Image 2024-01-30 at 11 43 02 AM](https://github.com/bithyve/bitcointribe/assets/62867694/17e3ba52-f573-4995-8521-81ebb6805b02)

**Comment by cakesoft-shyam** [comment]
![IMG_3820](https://github.com/bithyve/bitcointribe/assets/62867694/61c9b3c8-b518-4355-9867-faccd4b3e368)
![IMG_3821](https://github.com/bithyve/bitcointribe/assets/62867694/669abe66-9db7-45b2-9c21-bee00889ff4f)

**Comment by cakesoft-shyam** [comment]
![WhatsApp Image 2024-01-30 at 12 20 18 PM](https://github.com/bithyve/bitcointribe/assets/62867694/ab9cac89-a2dd-4272-a5da-f2b9c0118568)

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
