### ISSUE TITLE
Changed the modal's illustration image

### ISSUE THREAD

**Issue by akshay8551** [bithyve/bitcointribe#7026]
<img width="328" alt="Screenshot 2024-02-01 at 11 01 51 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/8905491f-78cc-406c-b802-b9dc885cf725">

**Comment by akshay8551** [comment]
<img width="328" alt="Screenshot 2024-02-01 at 11 02 59 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/d01f64a1-150b-4e2a-94fa-5d1da580b0cd">

**Comment by cakesoft-swati** [comment]
- Verified this issue on Tribe app v 2.4.0(629)
