### ISSUE TITLE
RGB: Attached file not showing up on my assets screen in ios.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#7028]
![IMG_1351](https://github.com/bithyve/bitcointribe/assets/62699947/2e5d72da-d01d-419f-a656-0258b7b23f20)

**Comment by akshay8551** [comment]
Done,

![Screenshot_20240208-173511_Bitcoin Tribe dev](https://github.com/bithyve/bitcointribe/assets/61345820/b87bde20-d1d1-476b-81bd-134f176dec72)
![Screenshot_20240208-173532_Bitcoin Tribe dev](https://github.com/bithyve/bitcointribe/assets/61345820/77161750-8e9a-4e91-80f9-e3511c298664)

**Comment by cakesoft-swati** [comment]
-  Verified this issue on Tribe app v 2.4.0(629)
