### ISSUE TITLE
RGB: UI issues 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#7030]
![Screenshot_2024-02-05-10-49-14-70_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/1f3e6257-7e24-41ae-a3d0-d71753c3ebbe)

- Not clear what is mandatory and what is not on creation screens

![Screenshot_2024-02-05-10-49-01-31_6ccb4bf936ab2cedd5e025652c6047ae](https://github.com/bithyve/bitcointribe/assets/62699947/9a462c8f-922a-44d9-84ca-deeeff7f92d2)
- Also not clear which one is send and which one is received.

**Comment by akshay8551** [comment]
1. 
<img width="328" alt="Screenshot 2024-02-06 at 3 42 18 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/24e65690-5b0d-46d4-9683-0aced1e321ba">
<img width="328" alt="Screenshot 2024-02-06 at 3 42 34 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/143c3fb5-de7e-46aa-9c2b-0b32c39bd6b9">

**Comment by akshay8551** [comment]
Done.

<img width="328" alt="Screenshot 2024-02-08 at 1 16 55 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/4ed92d0f-959a-4c4b-9c3b-fff0357f8933">

**Comment by akshay8551** [comment]
<img width="328" alt="Screenshot 2024-02-08 at 2 31 35 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/f7f534f9-cf67-4328-913d-f5f24261de1a">

**Comment by cakesoft-swati** [comment]
- Still having same issue on Tribe app v 2.4.0(629)

**Comment by Deveshshankar** [comment]
Completed in Version 2.4.1 (630)
