### ISSUE TITLE
BTC to INR currency: UI issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/bitcointribe#7031]
![File (6)](https://github.com/bithyve/bitcointribe/assets/62699947/9c159300-1724-461b-9294-aa61ccb4b2a5)
- INR value should have different comma placement

**Comment by akshay8551** [comment]
Comma is in the right place,

![Screenshot_20240208-130950_Bitcoin Tribe dev](https://github.com/bithyve/bitcointribe/assets/61345820/52ac6dbb-3f8d-4c0d-a398-9621af4216f9)

![Screenshot_20240208-131012_Bitcoin Tribe dev](https://github.com/bithyve/bitcointribe/assets/61345820/5751ebaa-68f0-4bef-9792-305bb3d32ad0)

**Comment by cakesoft-swati** [comment]
- Still having the same issue on Tribe app v 2.4.0(629)

**Comment by Deveshshankar** [comment]
Closing cc @akshay8551
