### ISSUE TITLE
Finalize insightful data regarding fees.

### ISSUE THREAD

**Issue by cakesoft-shyam** [bithyve/bitcointribe#7058]
What insights should we present to the user regarding fees and Bitcoin?

- [x] Insight Data - Fees

reference
- [Clark Moody](https://bitcoin.clarkmoody.com/dashboard/)
- [lookintobitcoin](https://www.lookintobitcoin.com/)

**Comment by Deveshshankar** [comment]
closing cc @cakesoft-shyam
