### ISSUE TITLE
Sending BTC screen UI 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#7066]
The sub heading is too small and also the gapping is not correct which results text cutting at bottom 
Live app 2.4.0 (629)

![screenshot_2024-02-12-08-57-36-14_20dc81889e0fe9e2ef2bddb793fc77ef_720](https://github.com/bithyve/bitcointribe/assets/107177634/16b21847-045f-4bfc-a8b2-3fbc74a4aac6)

**Comment by akshay8551** [comment]
Resolved,

<img width="328" alt="Screenshot 2024-02-12 at 10 40 17 AM" src="https://github.com/bithyve/bitcointribe/assets/61345820/b95067b9-f043-4bd7-87dc-243e8b58724a">

**Comment by Deveshshankar** [comment]
Completed
