### ISSUE TITLE
Toast message / Modal while creating asset

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#7076]
- [x] We need some CTA on RGB tab that shows that the test account needs to be funded or that RGB actions can't be done any more as there are no funds.

- [x] **Asset creation Animation**

Successful message / Error message modal

**Comment by akshay8551** [comment]
<img width="330" alt="Screenshot 2024-02-19 at 3 13 25 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/81a890e6-e610-413f-82f4-b478fe8dbfd7">
<img width="330" alt="Screenshot 2024-02-19 at 3 19 25 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/791ac470-418a-4751-ac0b-567a9676c40c">

**Comment by Deveshshankar** [comment]
Version 2.4.1 (630)
