### ISSUE TITLE
asset details screen changes

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#7083]
- [x] In the list of transaction alignment and send receive , arrow icon is missing

![img_3829_720](https://github.com/bithyve/bitcointribe/assets/107177634/ffa58806-dc49-4e75-9226-8e204a0f4ac5)
Refer design 
<img width="258" alt="Screenshot 2024-02-14 at 11 00 13 AM" src="https://github.com/bithyve/bitcointribe/assets/107177634/ad2b9b96-da34-415e-b902-52c539fa86cd">

Refer this XD link 
https://xd.adobe.com/view/513aecc1-ec34-4259-bf3e-956ddb5b60f3-0469/screen/0fc67eaf-b096-4954-b887-0e40444d95ec/

**Comment by akshay8551** [comment]
Done.
<img width="320" alt="Screenshot 2024-02-14 at 3 31 08 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/a7915f29-0421-49f8-bef0-cf04cdd8fd31">

**Comment by Deveshshankar** [comment]
Changes were done only in collectibles plz update in coins as well

**Comment by akshay8551** [comment]
<img width="322" alt="Screenshot 2024-02-21 at 3 07 39 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/483bb8ee-e905-4ece-8fe8-4b1a721df155">

**Comment by Deveshshankar** [comment]
Completed
