### ISSUE TITLE
Need to create modals for insufficient fund while S&R

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#7087]
Need to create modals for insufficient fund case  user will be redirected to Receive faucet in Test account

**Comment by Deveshshankar** [comment]
https://xd.adobe.com/view/aa7506c7-c534-4a62-b962-9fff771cbdd9-ff26/screen/f1488eb2-a4fa-489c-ac06-9862b8fe9d9a/specs/

**Comment by akshay8551** [comment]
Done. 
<img width="330" alt="Screenshot 2024-02-19 at 3 13 25 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/d606c031-51c1-4d96-a445-42f5e738daeb">
<img width="330" alt="Screenshot 2024-02-19 at 3 19 25 PM" src="https://github.com/bithyve/bitcointribe/assets/61345820/3299451b-bdf3-46ff-a8d9-2f793f6ddd02">

**Comment by Deveshshankar** [comment]
Version 2.4.1 (630)
