### ISSUE TITLE
Need to create a modal similar to Keeper 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#7111]
Need to create a modal after passcode creation 
![IMG_3904](https://github.com/bithyve/bitcointribe/assets/107177634/1c15c6de-8477-4bca-9bee-1e47850c6a44)

**Comment by vr-varad** [comment]
@Deveshshankar can u explain modal in sense what do u mean

**Comment by akshay8551** [comment]
Resolved,

![simulator_screenshot_0E7D71E9-C819-4FD5-83A0-DF583976E2AC](https://github.com/bithyve/bitcointribe/assets/61345820/7083d396-56db-4c5a-ad3a-f4a2d78769c5)

**Comment by Deveshshankar** [comment]
Can see modal implemented in 2.4.5 (634)
